import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { AiReviewReport } from "./types.js";
import { mapAreaToArtifact } from "./concernRegistry.js";

export interface ReportPaths {
  readonly jsonPath: string;
  readonly mdPath: string;
}

export function writeReviewReports(report: AiReviewReport, repoRoot: string): ReportPaths {
  const reportsDir = resolve(repoRoot, ".docforce/reports");
  mkdirSync(reportsDir, { recursive: true });

  const jsonPath = resolve(reportsDir, "ai-change-review.json");
  const mdPath = resolve(reportsDir, "ai-change-review.md");

  writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf-8");
  writeFileSync(mdPath, generateMarkdownReport(report), "utf-8");

  return { jsonPath, mdPath };
}

export function generateMarkdownReport(report: AiReviewReport): string {
  const lines: string[] = [];
  const result = report.result;
  const d = report.deterministic;

  lines.push("# DocForce AI Change Review");
  lines.push("");
  lines.push(`> Generated by DocForce v${report.docforceVersion}`);
  lines.push("");

  lines.push("## Deterministic Context");
  lines.push("");
  lines.push(`**Base:** ${report.baseRef}`);
  lines.push(`**Head:** ${report.headRef}`);
  lines.push(`**Architecture impact:** ${d.overallImpactLevel.toUpperCase()}`);
  lines.push(`**Manual review:** ${d.manualReviewRecommended ? "Yes" : "No"}`);
  if (d.manualReviewReason) {
    lines.push(`**Manual review reason:** ${d.manualReviewReason}`);
  }
  lines.push(`**Changed components:** ${d.changedComponents.length > 0 ? d.changedComponents.join(", ") : "none"}`);
  lines.push(`**Changed files:** ${d.changedFiles.length > 0 ? d.changedFiles.join(", ") : "none"}`);
  if (d.changedDomains.length > 0) {
    lines.push(`**Changed model domains:** ${d.changedDomains.join(", ")}`);
  }
  lines.push("");

  if (!result.triggered) {
    lines.push("## AI Interpretation");
    lines.push("");
    lines.push("AI review was **not triggered**.");
    lines.push("");
    lines.push(`Reason: ${result.triggerReason ?? "No trigger conditions met"}`);
    lines.push("");
    appendTrustNotice(lines);
    return lines.join("\n");
  }

  if (result.error) {
    lines.push("## AI Interpretation");
    lines.push("");
    lines.push("AI review **failed**. Deterministic analysis is unchanged.");
    lines.push("");
    lines.push(`**Error:** ${result.error}`);
    lines.push("");
    if (result.triggerReason) {
      lines.push(`**Trigger:** ${result.triggerReason}`);
      lines.push("");
    }
    lines.push("Manual review recommended by the deterministic analyzer remains in effect.");
    lines.push("");
    appendTrustNotice(lines);
    return lines.join("\n");
  }

  const a = result.assessment;

  lines.push("## AI Interpretation");
  lines.push("");
  if (a) {
    lines.push(`**Behavioral change:** ${a.behavioralChangeDetected ? "Yes" : "No"}`);
    lines.push(`**Confidence:** ${a.confidence}`);
    lines.push(`**Summary:** ${a.summary}`);
  } else {
    lines.push("No assessment produced.");
  }
  if (result.triggerReason) {
    lines.push(`**Trigger:** ${result.triggerReason}`);
  }
  lines.push("");

  lines.push("## Concerns");
  lines.push("");
  if (a && a.concerns.length > 0) {
    lines.push("| Concern | Confidence |");
    lines.push("|---------|------------|");
    for (const concern of a.concerns) {
      lines.push(`| ${concern} | ${a.confidence} |`);
    }
  } else {
    lines.push("No behavioral/documentation concerns identified.");
  }
  lines.push("");

  lines.push("## Documentation Recommendations");
  lines.push("");
  if (a && a.documentationRecommendations.length > 0) {
    lines.push("| Area | Impact | Existing artifact | Action |");
    lines.push("|------|--------|-------------------|--------|");
    for (const rec of a.documentationRecommendations) {
      const mapping = mapAreaToArtifact(rec.area);
      const artifact = mapping.artifactId ?? "none (manual documentation area)";
      const action = mapping.requiresHumanReview
        ? "Human review — no generated artifact exists"
        : rec.impact === "none"
          ? "No change"
          : "Review existing generated artifact";
      lines.push(`| ${rec.area} | ${rec.impact} | ${artifact} | ${action} |`);
    }
  } else {
    lines.push("No documentation recommendations.");
  }
  lines.push("");

  lines.push("## Evidence");
  lines.push("");
  if (a && a.evidence.length > 0) {
    for (const e of a.evidence) {
      const lineRange = e.startLine
        ? (e.endLine ? `:${e.startLine}-${e.endLine}` : `:${e.startLine}`)
        : "";
      lines.push(`- \`${e.path}${lineRange}\``);
    }
  } else {
    lines.push("No valid repository evidence references.");
  }
  lines.push("");

  lines.push("## Uncertainties");
  lines.push("");
  if (a && a.uncertainties.length > 0) {
    for (const u of a.uncertainties) {
      lines.push(`- ${u}`);
    }
  } else {
    lines.push("None recorded.");
  }
  lines.push("");

  lines.push("## Human Confirmation");
  lines.push("");
  if (a?.requiresHumanConfirmation) {
    lines.push("**Required.** A human should confirm this interpretation before changing documentation.");
  } else if (d.manualReviewRecommended) {
    lines.push("Deterministic analysis still recommends manual review even if the AI assessment is low-risk.");
  } else {
    lines.push("Not required by the AI assessment.");
  }
  lines.push("");

  if (result.conflicts.length > 0) {
    lines.push("## Deterministic vs AI Conflicts");
    lines.push("");
    lines.push("| Field | Deterministic fact | AI claim | Resolution |");
    lines.push("|-------|-------------------|----------|------------|");
    for (const c of result.conflicts) {
      lines.push(`| ${c.field} | ${c.deterministicFact} | ${c.aiClaim} | ${c.resolution} |`);
    }
    lines.push("");
  }

  if (!result.validationPassed || result.validationErrors.length > 0) {
    lines.push("## Validation");
    lines.push("");
    lines.push(`**Passed:** ${result.validationPassed ? "Yes" : "No"}`);
    if (result.evidenceDowngraded) {
      lines.push("**Evidence downgraded:** Yes");
    }
    for (const err of result.validationErrors) {
      lines.push(`- ${err}`);
    }
    lines.push("");
  }

  if (result.providerMetadata) {
    lines.push("## Provider metadata (operational, not product documentation)");
    lines.push("");
    lines.push(`- Provider: ${result.providerMetadata.providerName}`);
    if (result.providerMetadata.modelId) lines.push(`- Model: ${result.providerMetadata.modelId}`);
    if (result.providerMetadata.requestId) lines.push(`- Request: ${result.providerMetadata.requestId}`);
    if (result.providerMetadata.latencyMs !== undefined) lines.push(`- Latency: ${result.providerMetadata.latencyMs}ms`);
    if (result.providerMetadata.inputTokens !== undefined) lines.push(`- Input tokens: ${result.providerMetadata.inputTokens}`);
    if (result.providerMetadata.outputTokens !== undefined) lines.push(`- Output tokens: ${result.providerMetadata.outputTokens}`);
    lines.push("");
  }

  appendTrustNotice(lines);
  return lines.join("\n");
}

function appendTrustNotice(lines: string[]): void {
  lines.push("## Trust Notice");
  lines.push("");
  lines.push("AI interpretations are **not** deterministic repository facts.");
  lines.push("");
  lines.push("DocForce keeps three knowledge classes separate:");
  lines.push("");
  lines.push("1. **Deterministic facts** — established by scanners and the System Model.");
  lines.push("2. **AI interpretations** — reviewable inferences from supplied diffs.");
  lines.push("3. **Unknown / human** — intent, rationale, and anything the repository cannot prove.");
  lines.push("");
  lines.push("When AI contradicts a deterministic fact, the deterministic fact is retained.");
  lines.push("");
}
