import type { DocforceConfig } from "../config/types.js";

export function renderDocforceYaml(config: DocforceConfig): string {
  const include = config.scanning.include.map((item) => `    - "${escapeYaml(item)}"`).join("\n");
  const exclude = config.scanning.exclude.map((item) => `    - "${escapeYaml(item)}"`).join("\n");
  const org = config.publication?.organization.name ?? "";
  const lines = [
    "# Generated by `docforce init`. Review product metadata before committing.",
    `schemaVersion: "${escapeYaml(config.schemaVersion)}"`,
    "",
    "product:",
    `  name: "${escapeYaml(config.product.name)}"`,
    `  type: "${escapeYaml(config.product.type)}"`,
    `  description: "${escapeYaml(config.product.description)}"`,
    "",
    "scanning:",
    `  rootDir: "${escapeYaml(config.scanning.rootDir)}"`,
    "  include:",
    include || '    - "package.json"',
    "  exclude:",
    exclude,
    "",
    "analysis:",
    "  exclude: []",
    "",
    "output:",
    `  systemModel: "${escapeYaml(config.output.systemModel)}"`,
    "  docs:",
    `    technicalOverview: "${escapeYaml(config.output.docs.technicalOverview)}"`,
    `    technologyInventory: "${escapeYaml(config.output.docs.technologyInventory)}"`,
    `    architectureDiagram: "${escapeYaml(config.output.docs.architectureDiagram)}"`,
    `    dependencyGraph: "${escapeYaml(config.output.docs.dependencyGraph ?? "docs/generated/dependency-graph.mmd")}"`,
    `    architectureEvidence: "${escapeYaml(config.output.docs.architectureEvidence)}"`,
    `    technicalArchitecture: "${escapeYaml(config.output.docs.technicalArchitecture ?? "docs/generated/technical-architecture.md")}"`,
    "",
    "publication:",
    "  organization:",
    `    name: "${escapeYaml(org)}"`,
    "  document:",
    '    title: "Technical Architecture & Design Document"',
    "",
  ];
  return `${lines.join("\n")}\n`;
}

function escapeYaml(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
