import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DocumentationProposalReport } from "./types.js";
import { persistStoredProposal } from "../apply/store.js";
import { StoredProposalSchema } from "../apply/types.js";

export function writeProposalArtifacts(
  report: DocumentationProposalReport,
  repoRoot: string,
): { jsonPath: string; mdPath: string } {
  const proposalsDir = join(repoRoot, ".docforce", "proposals");
  const patchesDir = join(proposalsDir, "patches");
  const reportsDir = join(repoRoot, ".docforce", "reports");
  mkdirSync(patchesDir, { recursive: true });
  mkdirSync(reportsDir, { recursive: true });

  const latestJson = join(proposalsDir, "latest.json");
  const latestMd = join(proposalsDir, "latest.md");
  writeFileSync(latestJson, JSON.stringify(report, null, 2), "utf-8");
  const md = generateProposalMarkdown(report);
  writeFileSync(latestMd, md, "utf-8");

  for (const p of report.proposals) {
    const stored = StoredProposalSchema.safeParse({
      ...p,
      proposalId: p.proposalId ?? p.id,
    });
    if (stored.success) persistStoredProposal(stored.data, repoRoot);
    if (p.unifiedDiff) {
      const name = `${p.sectionId.replace(/[^a-zA-Z0-9._-]/g, "_")}.diff`;
      writeFileSync(join(patchesDir, name), p.unifiedDiff, "utf-8");
    }
  }

  const jsonPath = join(reportsDir, "documentation-proposal.json");
  const mdPath = join(reportsDir, "documentation-proposal.md");
  writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf-8");
  writeFileSync(mdPath, md, "utf-8");

  return { jsonPath, mdPath };
}

export function generateProposalMarkdown(report: DocumentationProposalReport): string {
  const s: string[] = [];
  s.push("# DocForce Documentation Proposal");
  s.push("");
  s.push(`> Generated by DocForce v${report.docforceVersion}`);
  s.push("");

  s.push("## Change Context");
  s.push("");
  s.push(`**Base:** ${report.baseRef}`);
  s.push(`**Head:** ${report.headRef}`);
  s.push(`**Deterministic impact:** ${report.overallImpact.toUpperCase()}`);
  s.push(`**Manual review:** ${report.manualReviewRecommended ? "Yes" : "No"}`);
  s.push(`**AI review confidence:** ${report.aiReviewConfidence ?? "n/a"}`);
  if (report.aiReviewSummary) s.push(`**AI review summary:** ${report.aiReviewSummary}`);
  s.push(`**Changed component:** ${report.changedComponents.length > 0 ? report.changedComponents.join(", ") : "(none)"}`);
  s.push(`**Changed files:** ${report.changedFiles.length > 0 ? report.changedFiles.map((f) => `\`${f}\``).join(", ") : "(none)"}`);
  s.push("");

  if (report.providerError) {
    s.push("## Status");
    s.push("");
    s.push(`Proposal generation unavailable: ${report.providerError}`);
    s.push("");
    s.push("Deterministic analysis is unchanged. No documentation files were modified.");
    s.push("");
    appendTrust(s);
    return s.join("\n");
  }

  s.push("## Proposed Documentation Changes");
  s.push("");
  if (report.proposals.length === 0 && report.manualActions.length === 0) {
    s.push("No documentation proposals.");
    s.push("");
  } else if (report.proposals.length > 0) {
    s.push("| Area | File | Section | Operation | Confidence | Human approval |");
    s.push("|------|------|---------|-----------|------------|----------------|");
    for (const p of report.proposals) {
      s.push(`| ${p.area} | ${p.targetPath} | ${p.sectionId} | ${p.operation} | ${p.confidence} | required |`);
    }
    s.push("");
  }

  if (report.manualActions.length > 0) {
    s.push("## Manual documentation action required");
    s.push("");
    for (const m of report.manualActions) {
      s.push(`- **${m.area}** (${m.impact}): ${m.reason}`);
    }
    s.push("");
  }

  for (const p of report.proposals) {
    s.push(`## Proposed Content — ${p.sectionId}`);
    s.push("");
    s.push(`**Title:** ${p.title}`);
    s.push(`**Summary:** ${p.summaryOfChange}`);
    s.push("");
    s.push("```markdown");
    s.push(p.proposedContent.trimEnd());
    s.push("```");
    s.push("");

    s.push("## Diff");
    s.push("");
    if (p.unifiedDiff) {
      s.push("```diff");
      s.push(p.unifiedDiff.trimEnd());
      s.push("```");
    } else {
      s.push("No textual diff (no-change).");
    }
    s.push("");

    s.push("## Evidence");
    s.push("");
    for (const e of p.evidence) {
      const range = e.startLine ? `:${e.startLine}${e.endLine ? `-${e.endLine}` : ""}` : "";
      s.push(`- \`${e.path}${range}\``);
    }
    s.push("");

    s.push("## Deterministic Facts Used");
    s.push("");
    if (p.deterministicFactsUsed.length === 0) s.push("None listed.");
    else for (const f of p.deterministicFactsUsed) s.push(`- ${f}`);
    s.push("");

    s.push("## AI Interpretations Used");
    s.push("");
    if (p.interpretationsUsed.length === 0) s.push("None listed.");
    else for (const f of p.interpretationsUsed) s.push(`- ${f}`);
    s.push("");

    s.push("## Assumptions");
    s.push("");
    if (p.assumptions.length === 0) s.push("None listed.");
    else for (const f of p.assumptions) s.push(`- ${f}`);
    s.push("");

    s.push("## Uncertainties");
    s.push("");
    if (p.uncertainties.length === 0) s.push("None listed.");
    else for (const f of p.uncertainties) s.push(`- ${f}`);
    s.push("");
  }

  s.push("## Conflicts");
  s.push("");
  if (report.conflicts.length === 0) {
    s.push("None recorded.");
  } else {
    for (const c of report.conflicts) {
      s.push(`- ${c.field}: deterministic \`${c.deterministicFact}\` vs AI \`${c.aiClaim}\` — ${c.resolution}`);
    }
  }
  s.push("");

  appendTrust(s);
  return s.join("\n");
}

function appendTrust(s: string[]): void {
  s.push("## Trust Notice");
  s.push("");
  s.push("This is an **AI-assisted documentation draft**. It has **not** been applied.");
  s.push("");
  s.push("No files under `docs/` were modified. Human approval is required before any future apply step.");
  s.push("");
  s.push("Deterministic-owned generated documentation is out of scope for this proposal engine.");
  s.push("");
}