import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ApprovalRecord, ProposalApplicationReport } from "./types.js";
import { DOCFORCE_VERSION } from "../version.js";

export function writeApplicationReports(
  report: ProposalApplicationReport,
  repoRoot: string,
): { jsonPath: string; mdPath: string } {
  const reportsDir = join(repoRoot, ".docforce", "reports");
  mkdirSync(reportsDir, { recursive: true });
  const jsonPath = join(reportsDir, "proposal-application.json");
  const mdPath = join(reportsDir, "proposal-application.md");
  writeFileSync(jsonPath, JSON.stringify(report, null, 2), "utf-8");
  writeFileSync(mdPath, generateApplicationMarkdown(report), "utf-8");
  return { jsonPath, mdPath };
}

export function writeApprovalRecord(record: ApprovalRecord, repoRoot: string): string {
  const dir = join(repoRoot, ".docforce", "approvals");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${record.proposalId}.json`);
  writeFileSync(path, JSON.stringify(record, null, 2), "utf-8");
  return path;
}

export function generateApplicationMarkdown(report: ProposalApplicationReport): string {
  const p = report.plan;
  const s: string[] = [];
  s.push("# DocForce Proposal Application");
  s.push("");
  s.push(`> Generated by DocForce v${report.docforceVersion}`);
  s.push("");

  s.push("## Proposal");
  s.push("");
  s.push(`**Proposal ID:** ${p.proposalId}`);
  s.push(`**Proposal fingerprint:** ${p.proposalFingerprint}`);
  s.push(`**Target:** ${p.targetPath}`);
  s.push(`**Section:** ${p.sectionId}`);
  s.push(`**Operation:** ${p.operation}`);
  s.push("");

  s.push("## Status");
  s.push("");
  s.push(statusLabel(p.status, p.applied));
  s.push("");
  if (p.staleReason) s.push(p.staleReason);
  if (p.invalidReason) s.push(p.invalidReason);
  s.push("");

  s.push("## Freshness");
  s.push("");
  s.push(`**Proposal model fingerprint:** ${p.modelFingerprint ?? "n/a"}`);
  s.push(`**Current model fingerprint:** ${p.currentModelFingerprint ?? "n/a"}`);
  s.push(`**Original section hash:** ${p.oldContentHash ?? "n/a"}`);
  s.push(`**Current section hash:** ${p.currentContentHash ?? "n/a"}`);
  s.push(`**Proposed section hash:** ${p.proposedContentHash ?? "n/a"}`);
  s.push("");

  s.push("## Validation");
  s.push("");
  s.push(`**Pre-apply:** ${p.preApplyErrors.length === 0 ? "passed" : p.preApplyErrors.join("; ")}`);
  s.push(`**Post-apply:** ${p.applied ? (p.postApplyErrors.length === 0 ? "passed" : p.postApplyErrors.join("; ")) : "not applied"}`);
  if (p.rolledBack) s.push("**Rollback:** original file restored");
  s.push("");

  s.push("## Applied Change");
  s.push("");
  if (p.sectionDiff) {
    s.push("```diff");
    s.push(p.sectionDiff.trimEnd());
    s.push("```");
  } else {
    s.push("No section diff (no-change, already applied, or not applied).");
  }
  s.push("");

  s.push("## Evidence");
  s.push("");
  if (p.evidence.length === 0) {
    s.push("None recorded.");
  } else {
    for (const e of p.evidence) {
      const range = e.startLine ? `:${e.startLine}${e.endLine ? `-${e.endLine}` : ""}` : "";
      s.push(`- \`${e.path}${range}\``);
    }
  }
  s.push("");

  s.push("## Trust Notice");
  s.push("");
  s.push("The applied text originated from a previously generated AI-assisted proposal and was applied only after an explicit application command.");
  s.push("");
  s.push("No new AI inference was performed. No Git commit was created.");
  s.push("");
  s.push("Proposal fingerprint is an integrity check against accidental corruption. It is not tamper-proof authentication.");
  s.push("");
  s.push(`DocForce ${DOCFORCE_VERSION}.`);
  s.push("");
  return s.join("\n");
}

function statusLabel(status: string, applied: boolean): string {
  if (applied) return "APPLIED";
  switch (status) {
    case "ready": return "READY";
    case "stale": return "STALE";
    case "invalid": return "INVALID";
    case "no-change": return "NO CHANGE";
    case "already-applied": return "ALREADY APPLIED / NO CHANGE";
    case "revalidation-required": return "REVALIDATION REQUIRED";
    default: return status.toUpperCase();
  }
}
