import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { sanitizePath, sanitizeUntrustedText } from "./sanitize.js";
import { statusLabel } from "./summary.js";
import type { PullRequestDocumentationAssessment } from "./types.js";

/**
 * Write the detailed local assessment. This is the long-form counterpart to
 * the concise pull-request surface and is the only artifact produced when
 * running with --no-publish.
 */
export function writePrAssessmentReports(
  assessment: PullRequestDocumentationAssessment,
  repoRoot: string,
): { jsonPath: string; mdPath: string } {
  const reportsDir = join(repoRoot, ".docforce", "reports");
  mkdirSync(reportsDir, { recursive: true });

  const jsonPath = join(reportsDir, "pr-assessment.json");
  const mdPath = join(reportsDir, "pr-assessment.md");

  writeFileSync(jsonPath, JSON.stringify(assessment, null, 2), "utf-8");
  writeFileSync(mdPath, renderDetailedReport(assessment), "utf-8");

  return { jsonPath, mdPath };
}

export function renderDetailedReport(assessment: PullRequestDocumentationAssessment): string {
  const s: string[] = [];
  const pr = assessment.pullRequest;

  s.push("# DocForce Pull Request Documentation Assessment");
  s.push("");
  s.push(`> Generated by DocForce v${assessment.docforceVersion}`);
  s.push("");

  s.push("## Pull Request");
  s.push("");
  s.push(`| Field | Value |`);
  s.push(`|-------|-------|`);
  s.push(`| Repository | ${pr.repository ? sanitizePath(pr.repository) : "n/a (local preview)"} |`);
  s.push(`| Pull request | ${pr.number ?? "n/a"} |`);
  s.push(`| Base | ${sanitizePath(pr.baseRef)}${pr.baseSha ? ` (${sanitizePath(pr.baseSha)})` : ""} |`);
  s.push(`| Head | ${sanitizePath(pr.headRef)}${pr.headSha ? ` (${sanitizePath(pr.headSha)})` : ""} |`);
  s.push(`| From fork | ${pr.fromFork ? "Yes" : "No"} |`);
  s.push(`| Status | **${statusLabel(assessment.status)}** |`);
  s.push("");

  s.push("## Status Reasons");
  s.push("");
  for (const reason of assessment.statusReasons) {
    s.push(`- ${sanitizeUntrustedText(reason, 400)}`);
  }
  s.push("");

  s.push("## Change Impact");
  s.push("");
  s.push(`**Files changed:** ${assessment.changedFiles.length} (${assessment.productRelevantFileCount} product-relevant)`);
  s.push("");
  s.push(`**Architecture impact:** ${assessment.deterministicImpact.overallImpactLevel.toUpperCase()}`);
  s.push("");
  s.push(
    `**Changed model domains:** ${assessment.deterministicImpact.changedDomains.length > 0 ? assessment.deterministicImpact.changedDomains.join(", ") : "none"}`,
  );
  s.push("");

  if (assessment.changedFiles.length > 0) {
    s.push("| File | Change | Category |");
    s.push("|------|--------|----------|");
    for (const file of assessment.changedFiles) {
      s.push(`| ${sanitizePath(file.path)} | ${file.changeType} | ${file.category} |`);
    }
    s.push("");
  }

  s.push("## Deterministic Documentation");
  s.push("");
  if (assessment.deterministicDocs.error) {
    s.push(`Unavailable: ${sanitizeUntrustedText(assessment.deterministicDocs.error)}`);
    s.push("");
  } else {
    s.push("| Artifact | Path | Status | Reason |");
    s.push("|----------|------|--------|--------|");
    for (const artifact of assessment.deterministicDocs.artifacts) {
      s.push(
        `| ${sanitizePath(artifact.artifact)} | ${sanitizePath(artifact.path)} | ${artifact.status.toUpperCase()} | ${sanitizePath(artifact.reason)} |`,
      );
    }
    s.push("");
  }

  s.push("## Behavioral Review");
  s.push("");
  s.push(`**Manual review recommended:** ${assessment.deterministicImpact.manualReviewRecommended ? "Yes" : "No"}`);
  if (assessment.deterministicImpact.manualReviewReason) {
    s.push("");
    s.push(`> ${sanitizeUntrustedText(assessment.deterministicImpact.manualReviewReason, 400)}`);
  }
  s.push("");
  s.push(`**AI review:** ${assessment.aiReview.status.toUpperCase()} — ${sanitizeUntrustedText(assessment.aiReview.reason, 300)}`);
  if (assessment.aiReview.providerName) {
    s.push("");
    s.push(`**Provider:** ${sanitizeUntrustedText(assessment.aiReview.providerName, 60)}`);
  }
  if (assessment.aiReview.error) {
    s.push("");
    s.push(`**AI error:** ${sanitizeUntrustedText(assessment.aiReview.error, 300)}`);
  }
  if (assessment.aiReview.status === "completed") {
    s.push("");
    s.push(`**Behavioral change detected:** ${assessment.aiReview.behavioralChangeDetected ? "Yes" : "No"}`);
    s.push("");
    s.push(`**Summary (AI interpretation):** ${sanitizeUntrustedText(assessment.aiReview.summary ?? "", 600)}`);
    s.push("");
    s.push(`**Concerns:** ${assessment.aiReview.concerns.join(", ") || "none"}`);
    s.push("");
    s.push(`**Confidence:** ${assessment.aiReview.confidence ?? "n/a"}`);
  }
  s.push("");

  if (assessment.aiReview.conflicts.length > 0) {
    s.push("### AI vs Deterministic Conflicts");
    s.push("");
    for (const conflict of assessment.aiReview.conflicts) {
      s.push(
        `- ${sanitizePath(conflict.field)}: AI claimed "${sanitizeUntrustedText(conflict.aiClaim, 120)}" — deterministic fact "${sanitizeUntrustedText(conflict.deterministicFact, 120)}" retained.`,
      );
    }
    s.push("");
  }

  s.push("## AI Documentation Proposals");
  s.push("");
  if (assessment.proposals.length === 0) {
    s.push("No proposal needed.");
  } else {
    s.push("| State | Area | Target | Detail |");
    s.push("|-------|------|--------|--------|");
    for (const proposal of assessment.proposals) {
      s.push(
        `| ${proposal.state} | ${sanitizePath(proposal.area ?? "n/a")} | ${sanitizePath(proposal.targetPath ?? "n/a")} | ${sanitizePath(proposal.detail)} |`,
      );
    }
  }
  s.push("");

  s.push("## Actions");
  s.push("");
  if (assessment.actions.length === 0) {
    s.push("None.");
  } else {
    for (const action of assessment.actions) {
      const mark = action.resolved ? "x" : " ";
      s.push(`- [${mark}] (${action.kind}) ${sanitizeUntrustedText(action.description, 300)}`);
      if (action.command) s.push(`  - \`${sanitizeUntrustedText(action.command, 200)}\``);
    }
  }
  s.push("");

  s.push("## Policy");
  s.push("");
  s.push("```json");
  s.push(JSON.stringify(assessment.policy, null, 2));
  s.push("```");
  s.push("");

  s.push("---");
  s.push("");
  s.push("DocForce performed no write operations against documentation, Git, or the pull request branch.");
  s.push("");
  s.push("Deterministic findings are evidence-backed. AI interpretations, where present, are labeled and require human confirmation.");
  s.push("");

  return s.join("\n");
}
