import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DocumentationUpdatePlan } from "./types.js";

export function generateUpdateReports(
  plan: DocumentationUpdatePlan,
  repoRoot: string,
): { jsonPath: string; mdPath: string } {
  const reportsDir = join(repoRoot, ".docforce", "reports");
  mkdirSync(reportsDir, { recursive: true });

  const jsonPath = join(reportsDir, "documentation-update.json");
  const mdPath = join(reportsDir, "documentation-update.md");

  writeFileSync(jsonPath, JSON.stringify(plan, null, 2), "utf-8");
  writeFileSync(mdPath, generateMarkdown(plan), "utf-8");

  return { jsonPath, mdPath };
}

function generateMarkdown(plan: DocumentationUpdatePlan): string {
  const s: string[] = [];

  s.push("# DocForce Documentation Update Plan");
  s.push("");
  s.push(`> Generated by DocForce v${plan.docforceVersion}`);
  s.push("");

  s.push("## Comparison");
  s.push("");
  s.push(`**Base:** ${plan.baseRef}`);
  s.push(`**Head:** ${plan.headRef}`);
  s.push("");

  s.push("## Summary");
  s.push("");
  s.push(`| Metric | Value |`);
  s.push(`|--------|-------|`);
  s.push(`| Overall impact | **${plan.overallImpact.toUpperCase()}** |`);
  s.push(`| Model fingerprint | \`${plan.modelFingerprint.slice(0, 16)}\` |`);
  s.push(`| Manual review | ${plan.manualReviewRecommended ? "Yes" : "No"} |`);
  s.push(`| Validation | ${plan.validationPassed ? "Passed" : "FAILED"} |`);
  s.push(`| Applied | ${plan.applied ? "Yes" : "No (dry run)"} |`);
  s.push("");

  if (plan.manualReviewRecommended && plan.manualReviewReason) {
    s.push(`> **Manual review:** ${plan.manualReviewReason}`);
    s.push("");
  }

  s.push("## Documentation Update Plan");
  s.push("");
  s.push("| Artifact | Impact | Status |");
  s.push("|----------|--------|--------|");
  for (const a of plan.artifacts) {
    s.push(`| ${a.artifact} | ${a.impactLevel.toUpperCase()} | ${formatStatus(a.status)} |`);
  }
  s.push("");

  const updates = plan.artifacts.filter((a) => a.status === "would-update" || a.status === "would-create");
  if (updates.length > 0) {
    s.push("## Artifact Details");
    s.push("");
    for (const a of updates) {
      s.push(`### ${a.artifact}`);
      s.push("");
      s.push(`**Path:** ${a.path}`);
      s.push(`**Status:** ${formatStatus(a.status)}`);
      s.push(`**Reason:** ${a.reason}`);
      if (a.oldHash) s.push(`**Previous hash:** ${a.oldHash.slice(0, 12)}…`);
      if (a.newHash) s.push(`**New hash:** ${a.newHash.slice(0, 12)}…`);
      s.push("");
    }
  }

  if (plan.overallImpact === "none" && !plan.manualReviewRecommended) {
    s.push("No deterministic documentation updates required.");
    s.push("");
  }

  s.push("---");
  s.push("");
  s.push(`*Generated by DocForce v${plan.docforceVersion}.*`);
  s.push("");

  return s.join("\n");
}

function formatStatus(status: string): string {
  switch (status) {
    case "unaffected": return "UNAFFECTED";
    case "unchanged": return "UNCHANGED";
    case "would-create": return "WOULD CREATE";
    case "would-update": return "WOULD UPDATE";
    default: return status.toUpperCase();
  }
}
