import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ChangeImpactReport, EntityChange } from "./types.js";

export function generateReports(
  report: ChangeImpactReport,
  repoRoot: string,
): { jsonPath: string; mdPath: string } {
  const reportsDir = join(repoRoot, ".docforce", "reports");
  mkdirSync(reportsDir, { recursive: true });

  const jsonPath = join(reportsDir, "change-impact.json");
  const mdPath = join(reportsDir, "change-impact.md");

  const jsonReport = {
    ...report,
    modelDelta: {
      ...report.modelDelta,
      changedDomains: Array.from(report.modelDelta.changedDomains),
    },
  };
  writeFileSync(jsonPath, JSON.stringify(jsonReport, null, 2), "utf-8");

  const md = generateMarkdownReport(report);
  writeFileSync(mdPath, md, "utf-8");

  return { jsonPath, mdPath };
}

function generateMarkdownReport(report: ChangeImpactReport): string {
  const s: string[] = [];

  s.push("# DocForce Change Impact Report");
  s.push("");
  s.push(`> Generated by DocForce v${report.docforceVersion} on ${formatDate(report.generatedAt)}`);
  s.push("");

  s.push("## Comparison");
  s.push("");
  s.push(`**Base:** ${report.baseRef}`);
  s.push(`**Head:** ${report.headRef}`);
  s.push("");

  s.push("## Summary");
  s.push("");
  s.push(`| Metric | Value |`);
  s.push(`|--------|-------|`);
  s.push(`| Impact level | **${report.overallImpactLevel.toUpperCase()}** |`);
  s.push(`| Manual review | ${report.manualReviewRecommended ? "Yes" : "No"} |`);
  s.push(`| Files changed | ${report.fileChanges.length} |`);
  s.push(`| Model entity changes | ${report.modelDelta.entityChanges.length} |`);
  s.push(`| Relationship changes | ${report.modelDelta.relationshipChanges.length} |`);
  s.push("");

  if (report.manualReviewRecommended && report.manualReviewReason) {
    s.push(`> **Manual review recommended:** ${report.manualReviewReason}`);
    s.push("");
  }

  if (!report.modelDelta.isEmpty) {
    s.push("## Model Changes");
    s.push("");

    const domainGroups = groupByDomain(report.modelDelta.entityChanges);
    for (const [domain, changes] of domainGroups) {
      s.push(`### ${capitalize(domain)}`);
      s.push("");
      for (const change of changes) {
        const prefix = change.changeType === "added" ? "+"
          : change.changeType === "removed" ? "-"
          : "~";
        const detail = change.detail ? ` (${change.detail})` : "";
        s.push(`- ${prefix} ${change.name}${detail}`);
      }
      s.push("");
    }

    if (report.modelDelta.relationshipChanges.length > 0) {
      s.push("### Relationships");
      s.push("");
      for (const rc of report.modelDelta.relationshipChanges) {
        const prefix = rc.changeType === "added" ? "+" : "-";
        s.push(`- ${prefix} ${rc.from} → ${rc.to} (${rc.type})`);
      }
      s.push("");
    }
  } else {
    s.push("## Model Changes");
    s.push("");
    s.push("No deterministic architecture-documentation impact was detected.");
    s.push("");
    if (report.manualReviewRecommended) {
      s.push("> **Note:** This does not prove that documentation changes are unnecessary. Manual review is recommended because application behaviour changed outside the current static-analysis model.");
      s.push("");
    }
  }

  s.push("## Documentation Impact");
  s.push("");
  s.push("| Artifact | Affected | Impact | Reason |");
  s.push("|----------|----------|--------|--------|");
  for (const di of report.documentImpacts) {
    const affected = di.affected ? "Yes" : "No";
    s.push(`| ${di.artifact} | ${affected} | ${di.impactLevel} | ${di.reason} |`);
  }
  s.push("");

  s.push("## Changed Files");
  s.push("");
  if (report.fileChanges.length > 0) {
    for (const fc of report.fileChanges) {
      const status = fc.changeType === "added" ? "A"
        : fc.changeType === "removed" ? "D"
        : fc.changeType === "renamed" ? "R"
        : "M";
      const rename = fc.oldPath ? ` (from ${fc.oldPath})` : "";
      s.push(`- \`${status}\` ${fc.path}${rename}`);
    }
  } else {
    s.push("No file changes detected.");
  }
  s.push("");

  if (report.unknowns.length > 0 || report.manualReviewRecommended) {
    s.push("## Unknown / Manual Review");
    s.push("");
    if (report.manualReviewRecommended && report.manualReviewReason) {
      s.push(`- ${report.manualReviewReason}`);
    }
    for (const u of report.unknowns) {
      s.push(`- ${u}`);
    }
    s.push("");
  }

  s.push("---");
  s.push("");
  s.push(`*Generated by DocForce v${report.docforceVersion}. This report is ephemeral — regenerate with \`npm run docforce:impact\`.*`);
  s.push("");

  return s.join("\n");
}

function groupByDomain(
  changes: readonly EntityChange[],
): Map<string, EntityChange[]> {
  const groups = new Map<string, EntityChange[]>();
  for (const change of changes) {
    const list = groups.get(change.domain);
    if (list) {
      list.push(change);
    } else {
      groups.set(change.domain, [change]);
    }
  }
  return groups;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toISOString().split("T")[0]!;
  } catch {
    return iso;
  }
}
