import type { SystemModel } from "../model/types.js";
import type { DocforceConfig } from "../config/types.js";
import { buildDocumentationViewModel } from "../view/buildViewModel.js";
import { presentationConfig } from "../view/presentationConfig.js";
import type { DocumentationViewModel } from "../view/types.js";

export function generateApiInventory(model: SystemModel, config?: DocforceConfig): string {
  const view = buildDocumentationViewModel(model, presentationConfig(config));
  const sections: string[] = [];

  sections.push(`# ${model.product.name} — API Inventory`);
  sections.push("");
  sections.push("> Generated by DocForce from App Router route metadata.");
  sections.push("");

  if (view.apiRouteCount === 0) {
    sections.push("No local API routes were detected from repository evidence.");
    sections.push("");
    sections.push("---");
    sections.push("");
    sections.push("*Generated by DocForce. Do not edit manually — regenerate with `npm run docforce`.*");
    sections.push("");
    return sections.join("\n");
  }

  sections.push(
    `${view.apiRouteCount} local API route${view.apiRouteCount === 1 ? " was" : "s were"} detected across ${view.apiGroupCount} top-level route group${view.apiGroupCount === 1 ? "" : "s"}.`,
  );
  sections.push("");
  sections.push("Groups are the first path segment after `/api/` (repository path), not invented conceptual categories.");
  sections.push("");

  for (const group of view.apiGroups) {
    sections.push(`## ${group.group}`);
    sections.push("");
    sections.push("| Route | Methods | Source | Related component |");
    sections.push("|-------|---------|--------|-------------------|");
    for (const route of group.routes) {
      const methods = route.methods.length > 0 ? route.methods.join(", ") : "—";
      const related = route.relatedComponentId
        ? relatedLabel(route.relatedComponentId, model, view)
        : "—";
      sections.push(
        `| \`${route.path}\` | ${methods} | \`${route.sourceFile}\` | ${related} |`,
      );
    }
    sections.push("");
  }

  sections.push("---");
  sections.push("");
  sections.push("*Generated by DocForce. Do not edit manually — regenerate with `npm run docforce`.*");
  sections.push("");
  return sections.join("\n");
}

function relatedLabel(
  componentId: string,
  model: SystemModel,
  view: DocumentationViewModel,
): string {
  const viewComp = view.components.find((c) => c.id === componentId);
  if (viewComp) return `${viewComp.displayName} (\`${viewComp.path}\`)`;
  const modelComp = model.components.find((c) => c.id === componentId);
  if (modelComp) return `${modelComp.displayName ?? modelComp.name} (\`${modelComp.path}\`)`;
  return componentId;
}
