import type { Relationship, SystemModel } from "../model/types.js";
import type { DocforceConfig } from "../config/types.js";
import { generateSystemOverview } from "./architectureViews.js";
import { escMermaid, insufficientView, MermaidIds } from "./mermaid.js";
import { datastoreNodeId, integrationNodeId } from "../view/ids.js";

const INSUFFICIENT_DISCOVERY = insufficientView(
  "dependency-graph",
  "No evidence-backed software relationships were discovered.",
);

/**
 * High-level architecture overview. v1.1 uses the system-overview view
 * (category grouping) rather than dumping every package into one graph.
 * `architecture.mmd` keeps this path for Consumer #1 compatibility.
 */
export function generateArchitectureOverview(model: SystemModel, config: DocforceConfig): string {
  return generateSystemOverview(model, config);
}

/**
 * Generate the full dependency graph preserving all relationships.
 * This is the detailed engineering view with every component and relationship.
 */
export function generateDependencyGraph(model: SystemModel): string {
  const allComponentIds = new Set(model.components.map((c) => c.id));
  const activeRels = (model.relationships ?? []).filter(
    (r) => r.classification !== "unknown",
  );
  if (activeRels.length === 0) {
    return INSUFFICIENT_DISCOVERY;
  }
  return renderMermaid(model, activeRels, allComponentIds, false);
}

/**
 * Legacy entry point — generates the full dependency graph (backward compat).
 */
export function generateArchitectureDiagram(model: SystemModel): string {
  return generateDependencyGraph(model);
}

function renderMermaid(
  model: SystemModel,
  rels: Relationship[],
  includedComponentIds: Set<string>,
  isOverview: boolean,
): string {
  const lines: string[] = [];
  const diagramType = isOverview ? "Architecture Overview" : "Dependency Graph";

  lines.push(`%% ${model.product.name} ${diagramType}`);
  lines.push(`%% Generated by DocForce`);
  lines.push(`%% Edges are evidence-backed relationships`);
  lines.push("");
  lines.push("graph TD");

  const ids = new MermaidIds();

  const referencedNodes = new Set<string>();
  for (const rel of rels) {
    referencedNodes.add(rel.from);
    referencedNodes.add(rel.to);
  }

  const appComponents = model.components.filter(
    (c) => includedComponentIds.has(c.id) && referencedNodes.has(c.id),
  );
  if (appComponents.length > 0) {
    lines.push("");
    lines.push("  subgraph Application");
    for (const comp of appComponents) {
      const id = ids.id(comp.id);
      const label = comp.displayName ?? comp.name;
      lines.push(`    ${id}["${escMermaid(label)}"]`);
    }
    lines.push("  end");
  }

  const extNodes = new Set<string>();
  for (const integ of model.integrations) {
    const key = integrationNodeId(integ.name);
    if (referencedNodes.has(key)) extNodes.add(key);
  }
  if (extNodes.size > 0) {
    lines.push("");
    lines.push("  subgraph External");
    for (const integ of model.integrations) {
      const key = integrationNodeId(integ.name);
      if (!extNodes.has(key)) continue;
      const id = ids.id(key);
      lines.push(`    ${id}(("${escMermaid(integ.name)}"))`);
    }
    lines.push("  end");
  }

  const storeNodes = new Set<string>();
  for (const ds of model.datastores) {
    if (ds.type === "migration-directory" || ds.type === "schema-definition") continue;
    const key = datastoreNodeId(ds.name);
    if (referencedNodes.has(key)) storeNodes.add(key);
  }
  if (storeNodes.size > 0) {
    lines.push("");
    lines.push("  subgraph Storage");
    for (const ds of model.datastores) {
      if (ds.type === "migration-directory" || ds.type === "schema-definition") continue;
      const key = datastoreNodeId(ds.name);
      if (!storeNodes.has(key)) continue;
      const id = ids.id(key);
      lines.push(`    ${id}[("${escMermaid(ds.name)}")]`);
    }
    lines.push("  end");
  }

  const deviceNodes = (model.devices ?? []).filter((d) => referencedNodes.has(d.id));
  if (deviceNodes.length > 0) {
    lines.push("");
    lines.push("  subgraph Devices");
    for (const device of deviceNodes) {
      const id = ids.id(device.id);
      lines.push(`    ${id}["${escMermaid(device.name)}"]`);
    }
    lines.push("  end");
  }

  const infraNodes = model.infrastructure.filter((item) => referencedNodes.has(`infra:${item.name}`));
  if (infraNodes.length > 0) {
    lines.push("");
    lines.push("  subgraph Infrastructure");
    for (const item of infraNodes) {
      const id = ids.id(`infra:${item.name}`);
      lines.push(`    ${id}["${escMermaid(item.name)}"]`);
    }
    lines.push("  end");
  }

  lines.push("");
  for (const rel of rels) {
    const fromId = ids.get(rel.from);
    const toId = ids.get(rel.to);
    if (!fromId || !toId) continue;

    const label = formatEdgeLabel(rel);
    if (label) {
      lines.push(`  ${fromId} -- "${escMermaid(label)}" --> ${toId}`);
    } else {
      lines.push(`  ${fromId} --> ${toId}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function formatEdgeLabel(rel: Relationship): string | null {
  switch (rel.type) {
    case "imports": return null;
    case "calls-api": return "calls";
    case "persists-to": return "persists";
    case "receives-from": return "receives";
    case "spawns": return "spawns";
    case "invokes": return "invokes";
    case "depends-on": return "depends-on";
    case "reads-from": return "reads";
    case "writes-to": return "writes";
    case "publishes-to": return "publishes";
    case "deploys": return "deploys";
    case "configures": return "configures";
    case "runs-on": return "runs-on";
    case "attached-to": return "attached-to";
    case "communicates-over": return "over";
    case "mounts": return "mounts";
    default: {
      const _exhaustive: never = rel.type;
      return _exhaustive;
    }
  }
}
