import type { SystemModel, Relationship } from "../model/types.js";

export function generateArchitectureEvidence(model: SystemModel): string {
  const sections: string[] = [];

  sections.push(`# ${model.product.name} — Architecture Evidence Report`);
  sections.push("");
  sections.push(`> Generated by DocForce`);
  sections.push(`> This document makes DocForce's architectural understanding inspectable.`);
  sections.push(`> Every relationship listed below is backed by repository evidence.`);
  sections.push("");

  const rels = model.relationships ?? [];
  if (rels.length === 0) {
    sections.push("Architecture graph unavailable:");
    sections.push("No evidence-backed software relationships were discovered.");
    sections.push("");
    return sections.join("\n");
  }

  // Summary
  const observations = rels.filter((r) => r.classification === "observation");
  const inferences = rels.filter((r) => r.classification === "inference");

  sections.push("## Summary");
  sections.push("");
  sections.push(`| Classification | Count |`);
  sections.push(`|----------------|-------|`);
  sections.push(`| Observations | ${observations.length} |`);
  sections.push(`| Inferences | ${inferences.length} |`);
  sections.push(`| Total relationships | ${rels.length} |`);
  sections.push("");

  // Categorize relationships
  const internalRels = rels.filter(
    (r) => !r.to.startsWith("ext:") && !r.to.startsWith("store:"),
  );
  const externalRels = rels.filter((r) => r.to.startsWith("ext:"));
  const datastoreRels = rels.filter((r) => r.to.startsWith("store:"));

  if (internalRels.length > 0) {
    sections.push("## Internal Dependencies");
    sections.push("");
    renderRelationshipSection(internalRels, model, sections);
  }

  if (externalRels.length > 0) {
    sections.push("## External Service Connections");
    sections.push("");
    renderRelationshipSection(externalRels, model, sections);
  }

  if (datastoreRels.length > 0) {
    sections.push("## Datastore Connections");
    sections.push("");
    renderRelationshipSection(datastoreRels, model, sections);
  }

  sections.push("---");
  sections.push("");
  sections.push(`*Generated by DocForce. Do not edit manually — regenerate with \`npm run docforce\`.*`);
  sections.push("");

  return sections.join("\n");
}

function renderRelationshipSection(
  rels: Relationship[],
  model: SystemModel,
  sections: string[],
): void {
  const byFrom = new Map<string, Relationship[]>();
  for (const rel of rels) {
    const existing = byFrom.get(rel.from);
    if (existing) {
      existing.push(rel);
    } else {
      byFrom.set(rel.from, [rel]);
    }
  }

  for (const [from, fromRels] of [...byFrom.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const comp = model.components.find((c) => c.id === from);
    const heading = comp?.displayName ?? from;

    sections.push(`### ${heading}`);
    sections.push("");

    for (const rel of fromRels.sort((a, b) => a.to.localeCompare(b.to))) {
      const toLabel = resolveNodeLabel(rel.to, model);
      sections.push(`#### ${heading} → ${toLabel}`);
      sections.push("");
      sections.push(`**Relationship:** ${rel.type}`);
      sections.push("");
      sections.push(`**Classification:** ${rel.classification}`);
      sections.push("");
      sections.push(`**Confidence:** ${rel.confidence}`);
      sections.push("");

      if (rel.description) {
        sections.push(`**Description:** ${rel.description}`);
        sections.push("");
      }

      if (rel.evidence.length > 0) {
        sections.push("**Evidence:**");
        sections.push("");
        for (const ev of rel.evidence) {
          const loc = ev.line ? `${ev.sourceFile}:${ev.line}` : ev.sourceFile;
          const detail = ev.detail ? ` — ${ev.detail}` : "";
          sections.push(`- \`${loc}\`${detail}`);
        }
        sections.push("");
      }

      if (rel.derivedFrom && rel.derivedFrom.length > 0) {
        sections.push("**Derived from:**");
        sections.push("");
        for (const ref of rel.derivedFrom) {
          sections.push(`- \`${ref}\``);
        }
        sections.push("");
      }
    }
  }
}

function resolveNodeLabel(nodeId: string, model: SystemModel): string {
  if (nodeId.startsWith("ext:")) {
    const name = nodeId.slice(4);
    const integ = model.integrations.find(
      (i) => i.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") === name,
    );
    return integ?.name ?? name;
  }
  if (nodeId.startsWith("store:")) {
    const name = nodeId.slice(6);
    const ds = model.datastores.find(
      (d) => d.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") === name,
    );
    return ds?.name ?? name;
  }
  const comp = model.components.find((c) => c.id === nodeId);
  return comp?.displayName ?? comp?.name ?? nodeId;
}

