import type { DocforceConfig } from "../config/types.js";
import type { SystemModel } from "../model/types.js";
import { parseEnvNamesFromDetail, summarizeEnvNames, classifyEnvVar, type EnvArea } from "../view/envSummary.js";

const AREA_ORDER: EnvArea[] = [
  "service URLs",
  "credentials",
  "ports",
  "timeouts",
  "audio/device",
  "watchdog/operations",
  "runtime",
];

export function generateConfigurationInventory(model: SystemModel, _config?: DocforceConfig): string {
  const sections: string[] = [];
  sections.push(`# ${model.product.name} — Configuration Inventory`);
  sections.push("");
  sections.push("> Generated by DocForce. Variable names only — secret values are not documented.");
  sections.push("");

  const services = model.infrastructure.filter((item) => item.type === "docker-service");
  const allNames: { service: string; name: string; source: string; area: EnvArea }[] = [];
  for (const svc of services) {
    const names = parseEnvNamesFromDetail(svc.detail);
    const source = svc.provenance.evidence[0]?.sourceFile ?? "docker-compose.yml";
    for (const name of names) {
      allNames.push({ service: svc.name, name, source, area: classifyEnvVar(name) });
    }
  }

  if (allNames.length === 0) {
    sections.push("No Compose environment-variable names were discovered.");
    sections.push("");
    sections.push("---");
    sections.push("");
    sections.push("*Generated by DocForce. Do not edit manually — regenerate with `npm run docforce`.*");
    sections.push("");
    return sections.join("\n");
  }

  sections.push(`${allNames.length} environment-variable name${allNames.length === 1 ? " was" : "s were"} discovered from Compose service definitions.`);
  sections.push("");

  for (const area of AREA_ORDER) {
    const rows = allNames.filter((row) => row.area === area)
      .sort((a, b) => a.name.localeCompare(b.name) || a.service.localeCompare(b.service));
    if (rows.length === 0) continue;
    sections.push(`### ${area}`);
    sections.push("");
    sections.push("| Variable | Service | Source |");
    sections.push("|----------|---------|--------|");
    for (const row of rows) {
      sections.push(`| \`${row.name}\` | ${row.service} | \`${row.source}\` |`);
    }
    sections.push("");
  }

  const unique = [...new Set(allNames.map((row) => row.name))];
  sections.push(`Unique variable names: ${unique.length}. ${summarizeEnvNames(unique)}.`);
  sections.push("");
  sections.push("---");
  sections.push("");
  sections.push("*Generated by DocForce. Do not edit manually — regenerate with `npm run docforce`.*");
  sections.push("");
  return sections.join("\n");
}
