/**
 * Shared Mermaid helpers and the v1.1 insufficient-view policy.
 *
 * Policy B: specialized architecture views are always emitted. When evidence is
 * insufficient, the artifact is a clearly marked unavailable document — not an
 * empty `graph TD`. Always emitting the file keeps deterministic update and PR
 * currency hashing stable.
 */

export function insufficientView(kind: string, reason: string): string {
  return [
    `%% View unavailable: ${kind}`,
    "%% Architecture graph unavailable",
    "%% Insufficient evidence in the System Model to generate this architecture view.",
    `%% ${reason}`,
    "%% Generated by DocForce",
    "%% Policy: specialized views are always emitted so deterministic update and PR currency can hash them.",
    "",
  ].join("\n");
}

export function escMermaid(s: string): string {
  return s.replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export class MermaidIds {
  private readonly nodeIds = new Map<string, string>();
  private idCounter = 0;

  id(key: string): string {
    const existing = this.nodeIds.get(key);
    if (existing) return existing;
    const id = `N${this.idCounter++}`;
    this.nodeIds.set(key, id);
    return id;
  }

  has(key: string): boolean {
    return this.nodeIds.has(key);
  }

  get(key: string): string | undefined {
    return this.nodeIds.get(key);
  }

  /** Point another entity id at an already-emitted node (presentation alias only). */
  alias(key: string, existingId: string): void {
    this.nodeIds.set(key, existingId);
  }
}
