import type { DocforceConfig, TechnologyPresentation } from "../config/types.js";
import type { InfrastructureInfo, Provenance, SystemModel, TechnologyInfo } from "../model/types.js";
import { buildDocumentationViewModel } from "../view/buildViewModel.js";
import { presentationConfig } from "../view/presentationConfig.js";
import type { TechnologyViewItem } from "../view/types.js";
import { summarizeComposeDetail } from "../view/envSummary.js";
import { aggregateContainerImages } from "../view/infraPresentation.js";
import { integrationLabel } from "../view/integrationLabels.js";

const TECH_SECTIONS: readonly { heading: string; presentation: TechnologyPresentation }[] = [
  { heading: "Core Platform", presentation: "core-platform" },
  { heading: "Languages & Runtimes", presentation: "language-runtime" },
  { heading: "Frameworks", presentation: "framework" },
  { heading: "Data & Storage", presentation: "datastore" },
  { heading: "Infrastructure & Deployment", presentation: "infrastructure" },
  { heading: "External Services / Integrations", presentation: "external-integration" },
  { heading: "Major Capability Libraries", presentation: "capability-library" },
  { heading: "Supporting Libraries", presentation: "supporting-library" },
  { heading: "Development Tooling", presentation: "development-tool" },
];

export function generateTechnologyInventory(model: SystemModel, config?: DocforceConfig): string {
  const view = buildDocumentationViewModel(model, presentationConfig(config));
  const sections: string[] = [];

  sections.push(`# ${model.product.name} — Technology Inventory`);
  sections.push("");
  sections.push(`> Generated by DocForce`);
  sections.push("");
  sections.push("Presentation classes are derived from evidence and generic technology families.");
  sections.push("They do not change the underlying System Model.");
  sections.push("");

  if (model.runtime.length > 0 || model.languages.length > 0) {
    sections.push("## Languages & Runtimes");
    sections.push("");
    if (model.runtime.length > 0) {
      sections.push("### Runtime");
      sections.push("");
      sections.push("| Runtime | Version | Evidence | Confidence |");
      sections.push("|---------|---------|----------|------------|");
      for (const rt of model.runtime) {
        sections.push(
          `| ${rt.name} | ${rt.version ?? "not specified"} | ${formatEvidence(rt.provenance)} | ${rt.provenance.confidence} |`,
        );
      }
      sections.push("");
    }
    if (model.languages.length > 0) {
      sections.push("### Languages");
      sections.push("");
      sections.push("| Language | Version | Evidence | Confidence |");
      sections.push("|----------|---------|----------|------------|");
      for (const lang of model.languages) {
        sections.push(
          `| ${lang.name} | ${lang.version ?? "—"} | ${formatEvidence(lang.provenance)} | ${lang.provenance.confidence} |`,
        );
      }
      sections.push("");
    }
  }

  for (const section of TECH_SECTIONS) {
    if (section.heading === "Languages & Runtimes") {
      const extra = view.technologies.filter((t) => t.presentation === "language-runtime");
      if (extra.length === 0) continue;
      if (model.runtime.length === 0 && model.languages.length === 0) {
        sections.push(`## ${section.heading}`);
        sections.push("");
      } else {
        sections.push("### Declared language/runtime packages");
        sections.push("");
      }
      pushTechTable(sections, extra);
      continue;
    }

    const items = view.technologies.filter((t) => t.presentation === section.presentation);
    if (section.presentation === "infrastructure") {
      const infra = model.infrastructure;
      if (items.length === 0 && infra.length === 0) continue;
      sections.push(`## ${section.heading}`);
      sections.push("");
      pushInfrastructureGroups(sections, infra);
      if (items.length > 0) {
        sections.push("### Infrastructure technologies");
        sections.push("");
        pushTechTable(sections, items);
      }
      continue;
    }

    if (section.presentation === "datastore") {
      const datastores = model.datastores;
      if (items.length === 0 && datastores.length === 0) continue;
      sections.push(`## ${section.heading}`);
      sections.push("");
      if (datastores.length > 0) {
        sections.push("| Datastore | Type | Engine | Location | Evidence | Confidence |");
        sections.push("|-----------|------|--------|----------|----------|------------|");
        for (const ds of datastores) {
          sections.push(
            `| ${ds.name} | ${ds.type} | ${ds.engine ?? "—"} | ${ds.location ?? "—"} | ${formatEvidence(ds.provenance)} | ${ds.provenance.confidence} |`,
          );
        }
        sections.push("");
      }
      if (items.length > 0) {
        sections.push("### Datastore libraries");
        sections.push("");
        pushTechTable(sections, items);
      }
      continue;
    }

    if (section.presentation === "external-integration") {
      const integrations = model.integrations.filter((i) => i.type !== "system");
      if (items.length === 0 && integrations.length === 0) continue;
      sections.push(`## ${section.heading}`);
      sections.push("");
      if (integrations.length > 0) {
        sections.push("| Integration | Type | Direction | Protocol | Evidence | Confidence |");
        sections.push("|-------------|------|-----------|----------|----------|------------|");
        for (const integ of integrations) {
          sections.push(
            `| ${integrationLabel(integ.name)} | ${integ.type} | ${integ.direction} | ${integ.protocol ?? "—"} | ${formatEvidence(integ.provenance)} | ${integ.provenance.confidence} |`,
          );
        }
        sections.push("");
      }
      if (items.length > 0) {
        sections.push("### Integration libraries");
        sections.push("");
        pushTechTable(sections, items);
      }
      continue;
    }

    if (items.length === 0) continue;
    sections.push(`## ${section.heading}`);
    sections.push("");
    pushTechTable(sections, items);
  }

  const unknown = view.technologies.filter((t) => t.presentation === "unknown-dependency");
  if (unknown.length > 0) {
    sections.push("## Unclassified Dependencies");
    sections.push("");
    pushTechTable(sections, unknown);
  }

  if (view.technologies.length > 0) {
    sections.push("## Full Dependency Appendix");
    sections.push("");
    sections.push("Complete inventory. Presentation class does not remove or alter System Model entities.");
    sections.push("");
    sections.push("| Technology | Version | Model category | Presentation | Purpose | Source | Confidence |");
    sections.push("|------------|---------|----------------|--------------|---------|--------|------------|");
    const sorted = [...view.technologies].sort((a, b) => a.name.localeCompare(b.name));
    for (const tech of sorted) {
      const original = model.technologies.find((t) => t.name === tech.name);
      sections.push(
        `| ${tech.name} | ${tech.version ?? "—"} | ${tech.category} | ${tech.presentation}${tech.overridden ? " (override)" : ""} | ${tech.purpose ?? "—"} | ${formatTechEvidence(original)} | ${tech.confidence} |`,
      );
    }
    sections.push("");
  }

  if ((model.devices ?? []).length > 0) {
    sections.push("## Devices & Interfaces");
    sections.push("");
    sections.push("| Name | Kind | Detail | Evidence | Confidence |");
    sections.push("|------|------|--------|----------|------------|");
    for (const device of model.devices) {
      sections.push(
        `| ${device.name} | ${device.kind} | ${device.kind === "device-service" ? summarizeComposeDetail(device.detail) ?? "—" : device.detail ?? "—"} | ${formatEvidence(device.provenance)} | ${device.provenance.confidence} |`,
      );
    }
    sections.push("");
  }

  const coverage = model.coverage;
  if (coverage) {
    sections.push("## Discovery Coverage");
    sections.push("");
    sections.push("| Signal | Count |");
    sections.push("|--------|-------|");
    sections.push(`| TypeScript/JavaScript roots | ${coverage.typescriptJavascriptRoots} |`);
    sections.push(`| Python roots | ${coverage.pythonRoots} |`);
    sections.push(`| API routes | ${coverage.apiRoutes} |`);
    sections.push(`| Compose services | ${coverage.composeServices} |`);
    sections.push(`| Compose volumes | ${coverage.composeVolumes} |`);
    sections.push(`| Device evidence | ${coverage.deviceEvidence} |`);
    sections.push("");
    sections.push("These counts describe scanner coverage, not documentation completeness.");
    sections.push("");
  }

  sections.push("---");
  sections.push("");
  sections.push(`*Generated by DocForce. Do not edit manually — regenerate with \`npm run docforce\`.*`);
  sections.push("");

  return sections.join("\n");
}

function pushTechTable(sections: string[], items: readonly TechnologyViewItem[]): void {
  sections.push("| Technology | Version | Presentation | Purpose | Evidence | Confidence |");
  sections.push("|------------|---------|--------------|---------|----------|------------|");
  for (const tech of items) {
    sections.push(
      `| ${tech.name} | ${tech.version ?? "—"} | ${tech.presentation}${tech.overridden ? " (override)" : ""} | ${tech.purpose ?? "—"} | ${formatViewEvidence(tech)} | ${tech.confidence} |`,
    );
  }
  sections.push("");
}

function pushInfrastructureGroups(sections: string[], infra: readonly InfrastructureInfo[]): void {
  const groups: { heading: string; type: string }[] = [
    { heading: "Services", type: "docker-service" },
    { heading: "Systemd services", type: "systemd-service" },
    { heading: "Named volumes", type: "docker-volume" },
    { heading: "Networks", type: "docker-network" },
    { heading: "Fleet / deployment target", type: "device-fleet" },
  ];
  const used = new Set(groups.map((g) => g.type));
  for (const group of groups) {
    const items = infra.filter((i) => i.type === group.type);
    if (items.length === 0) continue;
    sections.push(`### ${group.heading}`);
    sections.push("");
    sections.push("| Name | Type | Detail | Evidence | Confidence |");
    sections.push("|------|------|--------|----------|------------|");
    for (const item of items) {
      const detail = item.type === "docker-service" ? summarizeComposeDetail(item.detail) : item.detail;
      sections.push(
        `| ${item.name} | ${item.type} | ${detail ?? "—"} | ${formatEvidence(item.provenance)} | ${item.provenance.confidence} |`,
      );
    }
    sections.push("");
  }
  const other = infra.filter((i) => !used.has(i.type));
  if (other.length > 0) {
    const images = aggregateContainerImages(other);
    const rest = other.filter((i) => i.type !== "container-image");
    if (images.length > 0 || rest.length > 0) {
      sections.push("### Other infrastructure");
      sections.push("");
      sections.push("| Name | Type | Detail | Evidence | Confidence |");
      sections.push("|------|------|--------|----------|------------|");
      for (const image of images) {
        const evidence = image.files[0] ? `\`${image.files[0]}\`${image.files.length > 1 ? ` (+${image.files.length - 1} more)` : ""}` : "—";
        sections.push(
          `| ${image.name} | container-image | ${image.detail} | ${evidence} | high |`,
        );
      }
      for (const item of rest) {
        sections.push(
          `| ${item.name} | ${item.type} | ${item.detail ?? "—"} | ${formatEvidence(item.provenance)} | ${item.provenance.confidence} |`,
        );
      }
      sections.push("");
    }
  }
}

function formatEvidence(provenance: Provenance): string {
  if (provenance.evidence.length === 0) return "—";
  const first = provenance.evidence[0]!;
  const extra = provenance.evidence.length > 1 ? ` (+${provenance.evidence.length - 1} more)` : "";
  return `\`${first.sourceFile}\`${extra}`;
}

function formatViewEvidence(tech: TechnologyViewItem): string {
  if (tech.evidence.length === 0) return "—";
  const first = tech.evidence[0]!;
  const extra = tech.evidence.length > 1 ? ` (+${tech.evidence.length - 1} more)` : "";
  return `\`${first.sourceFile}\`${extra}`;
}

function formatTechEvidence(tech: TechnologyInfo | undefined): string {
  if (!tech) return "—";
  return formatEvidence(tech.provenance);
}
