import type { DocforceConfig } from "../config/types.js";
import { resolveDocsOutputPath } from "../config/types.js";
import type { Relationship, SystemModel } from "../model/types.js";
import { buildDocumentationViewModel, overviewCategoryLabel } from "../view/buildViewModel.js";
import { presentationConfig } from "../view/presentationConfig.js";
import { componentResponsibilitySummary } from "../view/componentSummary.js";
import { classifyEnvVar, envAreas, parseEnvNamesFromDetail, type EnvArea } from "../view/envSummary.js";
import { aggregateContainerImages } from "../view/infraPresentation.js";
import { integrationLabel } from "../view/integrationLabels.js";
import { groupIntegrations } from "../view/integrationGroups.js";
import { serviceDisplayLabel } from "../view/serviceLabels.js";
import { datastoreNodeId } from "../view/ids.js";
import type { ComponentViewItem, DocumentationViewModel } from "../view/types.js";
import {
  generateDataArchitecture,
  generateDeploymentArchitecture,
  generateDeviceArchitecture,
  generateSoftwareArchitecture,
  generateSystemOverview,
} from "./architectureViews.js";

export function generateTechnicalArchitecture(model: SystemModel, config?: DocforceConfig): string {
  const cfg = presentationConfig(config);
  const view = buildDocumentationViewModel(model, cfg);
  const sections: string[] = [];

  sections.push(`# ${model.product.name} — Technical Architecture & Design`);
  sections.push("");
  sections.push("> Deterministic architecture document generated from the validated System Model. Supporting inventories remain in separate artifacts.");
  sections.push("");

  pushExecutiveSummary(sections, model, view);
  pushSystemContext(sections, model, view);
  pushArchitectureOverview(sections, model, cfg, view);
  pushSoftwareArchitecture(sections, model, cfg, view);
  pushTechnologyStack(sections, model, view, cfg);
  pushApiArchitecture(sections, model, view, cfg);
  pushDataArchitecture(sections, model, cfg);
  pushExternalIntegrations(sections, model, cfg);
  pushDeviceArchitecture(sections, model, cfg);
  pushDeploymentArchitecture(sections, model, cfg, view);
  pushRuntimeConfiguration(sections, model, cfg);
  pushCoverage(sections, view);
  pushUnknowns(sections, model);
  pushAppendices(sections, cfg);

  sections.push("---");
  sections.push("");
  sections.push("*Generated by DocForce. Do not edit manually — regenerate with `npm run docforce`.*");
  sections.push("");
  return sections.join("\n");
}

function pushExecutiveSummary(sections: string[], model: SystemModel, view: DocumentationViewModel): void {
  sections.push("## Executive Technical Summary");
  sections.push("");
  const type = model.product.type || "application";
  const description = firstSentence(model.product.description);
  sections.push(`${model.product.name} is ${article(type)} ${type}.${description ? ` ${description}` : ""}`);
  sections.push("");

  const compose = model.infrastructure.filter((item) => item.type === "docker-service");
  const fleet = model.infrastructure.find((item) => item.type === "device-fleet");
  const systemd = model.infrastructure.filter((item) => item.type === "systemd-service");
  const deviceIfaces = (model.devices ?? []).filter((d) => d.kind !== "device-service" && d.kind !== "device");
  const primary = view.components.filter((c) => c.presentation === "primary").map((c) => c.displayName);

  const facts: string[] = [];
  facts.push(`${model.components.length} software component${model.components.length === 1 ? "" : "s"}`);
  if (primary.length > 0) facts.push(`primary: ${primary.slice(0, 6).join(", ")}`);
  if (compose.length > 0) facts.push(`${compose.length} Compose service${compose.length === 1 ? "" : "s"}`);
  if (model.datastores.length > 0) facts.push(`${model.datastores.length} datastore${model.datastores.length === 1 ? "" : "s"}`);
  if (view.apiRouteCount > 0) facts.push(`${view.apiRouteCount} local API route${view.apiRouteCount === 1 ? "" : "s"}`);
  if (fleet) facts.push(`deployed as a Balena fleet application (${fleet.name})`);
  else if (compose.length > 0) facts.push("deployed with Docker Compose");
  else if (systemd.length > 0) facts.push(`deployed as systemd service ${systemd.map((s) => s.name).join(", ")}`);
  if (deviceIfaces.length > 0) {
    facts.push(`${deviceIfaces.length} evidenced device/peripheral interface${deviceIfaces.length === 1 ? "" : "s"}`);
  }

  sections.push(facts.map((fact) => `- ${fact}`).join("\n"));
  sections.push("");
  const languages = model.languages.map((l) => l.name);
  const runtime = model.runtime.map((r) => r.name);
  if (languages.length + runtime.length > 0) {
    sections.push(`Major languages/runtimes: ${[...runtime, ...languages].join(", ")}.`);
    sections.push("");
  }
}

function pushSystemContext(sections: string[], model: SystemModel, view: DocumentationViewModel): void {
  sections.push("## System Context");
  sections.push("");
  sections.push(`This document describes the technical boundary of the **${model.product.name}** repository, ${article(model.product.type)} ${model.product.type}. Facts below are limited to scanner coverage of this tree.`);
  sections.push("");
  sections.push("**Represented in this repository**");
  sections.push("");
  const inside: string[] = [];
  if (model.components.length > 0) {
    inside.push(`Software structure: ${model.components.length} component${model.components.length === 1 ? "" : "s"} (${model.components.map((c) => c.displayName ?? c.name).join(", ")}).`);
  }
  if (model.runtime.length + model.languages.length > 0) {
    inside.push(`Runtime/languages: ${[...model.runtime.map((r) => r.name), ...model.languages.map((l) => l.name)].join(", ")}.`);
  }
  if (model.datastores.length > 0) {
    inside.push(`Storage declared or used in-tree: ${model.datastores.map((d) => d.name).join(", ")}.`);
  }
  const compose = model.infrastructure.filter((i) => i.type === "docker-service");
  if (compose.length > 0) inside.push(`Deployment definitions: ${compose.length} Compose service${compose.length === 1 ? "" : "s"}.`);
  const fleet = model.infrastructure.find((i) => i.type === "device-fleet");
  if (fleet) inside.push(`Fleet manifest: ${fleet.name}.`);
  if (view.apiRouteCount > 0) inside.push(`Local HTTP API surface: ${view.apiRouteCount} App Router route${view.apiRouteCount === 1 ? "" : "s"}.`);
  const ifaces = (model.devices ?? []).filter((d) => d.kind === "peripheral" || d.kind === "communication-interface" || d.kind === "sensor");
  if (ifaces.length > 0) inside.push(`Device/peripheral interfaces evidenced in source: ${ifaces.map((d) => d.name).join(", ")}.`);
  if (inside.length === 0) inside.push("Product metadata from consumer configuration.");
  for (const line of inside) sections.push(`- ${line}`);
  sections.push("");

  sections.push("**Outside repository evidence**");
  sections.push("");
  const outside: string[] = [];
  const outbound = model.integrations.filter((i) => i.type !== "system");
  if (outbound.length > 0) {
    outside.push(`Outbound HTTP systems are referenced as hosts/SDKs (${outbound.length}); their implementations are not in this repository.`);
  }
  if (fleet) outside.push("Physical fleet devices are not inspected; only the fleet application manifest is represented.");
  outside.push("Scanner coverage is not a completeness claim. Undiscovered behavior may exist.");
  for (const line of outside) sections.push(`- ${line}`);
  sections.push("");
}

function pushArchitectureOverview(
  sections: string[],
  model: SystemModel,
  config: DocforceConfig,
  view: DocumentationViewModel,
): void {
  if (view.overviewNodes.length === 0) return;
  sections.push("## Architecture Overview");
  sections.push("");
  const byCategory = new Map<string, string[]>();
  for (const node of view.overviewNodes) {
    const label = overviewCategoryLabel(node.category);
    const list = byCategory.get(label) ?? [];
    list.push(node.label);
    byCategory.set(label, list);
  }
  sections.push("Major categories in the high-level view:");
  sections.push("");
  for (const [label, names] of byCategory) {
    sections.push(`- **${label}:** ${names.join(", ")}`);
  }
  sections.push("");
  const diagram = generateSystemOverview(model, config);
  embedDiagram(sections, diagram);
  sections.push(`See [\`system-overview.mmd\`](${rel(config, "systemOverview")}) for the standalone diagram.`);
  sections.push("");
}

function pushSoftwareArchitecture(
  sections: string[],
  model: SystemModel,
  config: DocforceConfig,
  view: DocumentationViewModel,
): void {
  const software = view.components.filter((c) => c.presentation !== "utility");
  if (software.length === 0 && model.components.length === 0) return;
  sections.push("## Software Architecture");
  sections.push("");
  sections.push("Software components are source identities. Compose/container names are deployment identities and are listed with the component when a mapping is evidenced.");
  sections.push("");

  const diagram = generateSoftwareArchitecture(model, config);
  embedDiagram(sections, diagram);
  sections.push(`See [\`software-architecture.mmd\`](${rel(config, "softwareArchitecture")}).`);
  sections.push("");

  for (const component of software.length > 0 ? software : view.components) {
    pushComponentSection(sections, component, model);
  }
}

function pushComponentSection(sections: string[], component: ComponentViewItem, model: SystemModel): void {
  const raw = model.components.find((c) => c.id === component.id);
  sections.push(`### ${component.displayName}`);
  sections.push("");
  sections.push(`- **Source path:** \`${component.path}\``);
  const summary = component.summary ?? (raw ? componentResponsibilitySummary(raw, model) : undefined);
  if (summary) sections.push(`- **Summary:** ${summary}`);
  const apiCount = (model.apiRoutes ?? []).filter((route) =>
    route.sourceFile === component.path || route.sourceFile.startsWith(`${component.path}/`),
  ).length;
  if (apiCount > 0) sections.push(`- **Local API ownership:** ${apiCount} App Router route${apiCount === 1 ? "" : "s"}.`);

  const localCalls = model.relationships.filter(
    (rel) => rel.from === component.id && rel.type === "calls-api" && rel.to.startsWith("infra:"),
  );
  if (localCalls.length > 0) {
    const parts = localCalls.map((rel) => {
      const name = rel.to.replace(/^infra:/, "");
      const path = httpPath(rel);
      return path ? `${name} (\`HTTP ${path}\`)` : name;
    });
    sections.push(`- **Local service calls:** ${parts.join("; ")}.`);
  }

  const stores = model.relationships.filter(
    (rel) => rel.from === component.id && rel.to.startsWith("store:") && (
      rel.type === "reads-from" || rel.type === "writes-to" || rel.type === "persists-to"
    ),
  );
  if (stores.length > 0) {
    sections.push(`- **Datastore operations:** ${stores.map((rel) => `${verb(rel.type)} ${rel.to.replace(/^store:/, "")}`).join("; ")}.`);
  }

  const ext = model.relationships.filter(
    (rel) => rel.from === component.id && rel.type === "calls-api" && rel.to.startsWith("ext:"),
  );
  if (ext.length > 0) {
    sections.push(`- **External integrations:** ${ext.length} outbound HTTP service${ext.length === 1 ? "" : "s"}.`);
  }

  const deploy = model.relationships.find((rel) => rel.from === component.id && rel.type === "deploys");
  const runs = model.relationships.find((rel) => rel.from === component.id && rel.type === "runs-on");
  if (deploy || runs) {
    const service = deploy?.to.replace(/^infra:/, "");
    const fleet = runs ? labelDevice(model, runs.to) : undefined;
    const bits = [
      service ? `Compose service \`${service}\`` : undefined,
      fleet ? `runs on ${fleet}` : undefined,
    ].filter(Boolean);
    sections.push(`- **Deployment:** ${bits.join("; ")}.`);
  }
  sections.push("");
}

function pushTechnologyStack(
  sections: string[],
  model: SystemModel,
  view: DocumentationViewModel,
  config: DocforceConfig,
): void {
  const techs = view.technologies;
  if (model.languages.length === 0 && model.runtime.length === 0 && techs.length === 0) return;
  sections.push("## Technology Stack");
  sections.push("");
  if (model.runtime.length > 0) {
    sections.push(`- **Runtimes:** ${model.runtime.map((r) => r.version ? `${r.name} ${r.version}` : r.name).join(", ")}`);
  }
  if (model.languages.length > 0) {
    sections.push(`- **Languages:** ${model.languages.map((l) => l.version ? `${l.name} ${l.version}` : l.name).join(", ")}`);
  }

  const byPresentation = (key: string) => techs.filter((t) => t.presentation === key);
  pushTechGroup(sections, "Core platform", byPresentation("core-platform"));
  pushTechGroup(sections, "Frameworks", byPresentation("framework"));
  const stores = model.datastores.filter((d) => d.type !== "migration-directory" && d.type !== "schema-definition");
  if (stores.length > 0) {
    sections.push(`- **Data/storage:** ${stores.map((d) => d.location ? `${d.name} (${d.location})` : d.name).join(", ")}`);
  }
  pushTechGroup(sections, "Infrastructure/deployment", byPresentation("infrastructure"));
  pushTechGroup(sections, "Major capability libraries", byPresentation("capability-library"));
  const integrations = byPresentation("external-integration");
  pushTechGroup(sections, "External integration libraries", integrations);

  sections.push("");
  sections.push("Supporting and development packages are omitted here.");
  sections.push(`The complete inventory is in [\`technology-inventory.md\`](${rel(config, "technologyInventory")}).`);
  sections.push("");
}

function pushTechGroup(sections: string[], heading: string, items: readonly { name: string; version?: string }[]): void {
  if (items.length === 0) return;
  sections.push(`- **${heading}:** ${items.map((item) => item.version ? `${item.name} ${item.version}` : item.name).join(", ")}`);
}

function pushApiArchitecture(
  sections: string[],
  _model: SystemModel,
  view: DocumentationViewModel,
  config: DocforceConfig,
): void {
  if (view.apiRouteCount === 0) return;
  sections.push("## Local API Architecture");
  sections.push("");
  sections.push(`${view.apiRouteCount} local API route${view.apiRouteCount === 1 ? " was" : "s were"} detected across ${view.apiGroupCount} top-level path group${view.apiGroupCount === 1 ? "" : "s"}. Groups are the first segment after \`/api/\`.`);
  sections.push("");
  sections.push("| Group | Routes |");
  sections.push("|-------|--------|");
  const sorted = [...view.apiGroups].sort((a, b) => b.routes.length - a.routes.length || a.group.localeCompare(b.group));
  for (const group of sorted) {
    sections.push(`| \`${group.group}\` | ${group.routes.length} |`);
  }
  sections.push("");
  sections.push(`Full paths and methods: [\`api-inventory.md\`](${rel(config, "apiInventory")}).`);
  sections.push("");
}

function pushDataArchitecture(sections: string[], model: SystemModel, config: DocforceConfig): void {
  const stores = model.datastores.filter((d) => d.type !== "migration-directory" && d.type !== "schema-definition");
  if (stores.length === 0) return;
  sections.push("## Data Architecture");
  sections.push("");
  for (const store of stores) {
    const id = datastoreNodeId(store.name);
    const rels = model.relationships.filter((rel) => rel.to === id);
    const location = store.location ? ` (named database \`${store.location}\`)` : "";
    sections.push(`- **${store.name}** — ${store.type}${store.engine ? `, engine ${store.engine}` : ""}${location}`);
    if (rels.length === 0) {
      sections.push("  - No operation relationship could be established from repository source.");
    } else {
      for (const rel of rels) {
        sections.push(`  - ${rel.from} ${verb(rel.type)} this store`);
      }
    }
  }
  sections.push("");
  embedDiagram(sections, generateDataArchitecture(model, config));
  sections.push(`See [\`data-architecture.mmd\`](${rel(config, "dataArchitecture")}).`);
  sections.push("");
}

function pushExternalIntegrations(sections: string[], model: SystemModel, config: DocforceConfig): void {
  const integrations = model.integrations.filter((i) => i.type !== "system");
  if (integrations.length === 0) return;
  sections.push("## External Integrations");
  sections.push("");
  const groups = groupIntegrations(integrations.map((i) => i.name));
  for (const group of groups) {
    if (group.family === "ungrouped") {
      const integ = integrations.find((i) => i.name === group.members[0]);
      sections.push(`- **${integrationLabel(group.members[0]!)}** — ${integ?.type ?? "external-api"}${integ?.protocol ? `, ${integ.protocol}` : ""}`);
    } else {
      sections.push(`- **${group.label}**`);
      for (const member of group.members) {
        sections.push(`  - ${integrationLabel(member)}`);
      }
    }
  }
  sections.push("");
  sections.push("Grouping is presentation-only. Canonical hosts remain in the inventory and evidence artifacts.");
  sections.push("");
}

function pushDeviceArchitecture(sections: string[], model: SystemModel, config: DocforceConfig): void {
  const devices = (model.devices ?? []).filter((d) => d.kind !== "device-service");
  if (devices.length === 0) return;
  sections.push("## Device & Peripheral Architecture");
  sections.push("");
  sections.push("Only interfaces evidenced in this repository are listed. Physical hardware is not observed. Undocumented hardware families are omitted rather than assumed.");
  sections.push("");
  sections.push("| Name | Kind | Detail |");
  sections.push("|------|------|--------|");
  for (const device of devices) {
    sections.push(`| ${device.name} | ${device.kind} | ${device.detail ?? "—"} |`);
  }
  sections.push("");
  const rels = model.relationships.filter(
    (rel) => (rel.type === "attached-to" || rel.type === "communicates-over") && devices.some((d) => d.id === rel.to),
  );
  if (rels.length > 0) {
    sections.push("Evidence-backed connections:");
    sections.push("");
    for (const rel of rels) {
      sections.push(`- ${rel.from} ${rel.type === "communicates-over" ? "communicates over" : "attached to"} ${labelDevice(model, rel.to)}`);
    }
    sections.push("");
  }
  embedDiagram(sections, generateDeviceArchitecture(model, config));
  sections.push(`See [\`device-architecture.mmd\`](${rel(config, "deviceArchitecture")}).`);
  sections.push("");
}

function pushDeploymentArchitecture(
  sections: string[],
  model: SystemModel,
  config: DocforceConfig,
  view: DocumentationViewModel,
): void {
  const services = model.infrastructure.filter((i) => i.type === "docker-service" || i.type === "systemd-service");
  const fleet = model.infrastructure.filter((i) => i.type === "device-fleet");
  if (services.length === 0 && fleet.length === 0) return;
  sections.push("## Deployment Architecture");
  sections.push("");
  if (fleet.length > 0) {
    sections.push(`**Fleet / deployment target:** ${fleet.map((item) => item.name).join(", ")}`);
    sections.push("");
  }
  const softwareNames = new Set(model.components.map((c) => c.id).concat(model.components.map((c) => c.name)));
  if (services.length > 0) {
    sections.push("### Services");
    sections.push("");
    for (const svc of services) {
      const label = svc.type === "docker-service" ? serviceDisplayLabel(svc.name, softwareNames) : svc.name;
      const mapped = model.relationships.find((rel) => rel.type === "deploys" && rel.to === `infra:${svc.name}`);
      const mapping = mapped ? ` — software component \`${mapped.from}\`` : "";
      const detail = flagshipServiceDetail(svc.detail);
      sections.push(`- **${label}** (\`${svc.name}\`)${mapping}${detail ? ` — ${detail}` : ""}`);
    }
    sections.push("");
  }

  const depends = model.relationships.filter((rel) => rel.type === "depends-on" && rel.from.startsWith("infra:"));
  if (depends.length > 0) {
    sections.push("Service dependencies:");
    sections.push("");
    for (const rel of depends) {
      sections.push(`- \`${rel.from.replace(/^infra:/, "")}\` depends_on \`${rel.to.replace(/^infra:/, "")}\``);
    }
    sections.push("");
  }

  const volumes = model.infrastructure.filter((i) => i.type === "docker-volume");
  const mounts = model.relationships.filter((rel) => rel.type === "mounts");
  if (volumes.length > 0) {
    sections.push("### Named volumes");
    sections.push("");
    for (const vol of volumes) {
      const usedBy = mounts.filter((rel) => rel.to === `infra:${vol.name}`);
      const usage = usedBy.length > 0
        ? usedBy.map((rel) => {
          const svc = rel.from.replace(/^infra:/, "");
          const target = mountTarget(rel);
          return target ? `${svc} at \`${target}\`` : svc;
        }).join("; ")
        : "no evidenced service mount";
      sections.push(`- **${vol.name}** — ${usage}`);
    }
    sections.push("");
  }

  const images = aggregateContainerImages(model.infrastructure.filter((i) => i.type === "container-image"));
  if (images.length > 0) {
    sections.push("### Container images");
    sections.push("");
    for (const image of images) {
      sections.push(`- **${image.name}** — used by ${image.count} Dockerfile${image.count === 1 ? "" : "s"}`);
    }
    sections.push("");
  }

  const ports = model.infrastructure.filter((i) => i.type === "exposed-port");
  if (ports.length > 0) {
    sections.push(`Exposed ports: ${ports.map((p) => p.name).join(", ")}.`);
    sections.push("");
  }

  embedDiagram(sections, generateDeploymentArchitecture(model, config));
  sections.push(`See [\`deployment-architecture.mmd\`](${rel(config, "deploymentArchitecture")}).`);
  sections.push("");
  void view;
}

function pushRuntimeConfiguration(sections: string[], model: SystemModel, config: DocforceConfig): void {
  const services = model.infrastructure.filter((item) => item.type === "docker-service");
  const names: string[] = [];
  for (const svc of services) names.push(...parseEnvNamesFromDetail(svc.detail));
  if (names.length === 0) return;
  sections.push("## Runtime Configuration");
  sections.push("");
  sections.push(`${names.length} environment-variable names were discovered from Compose service definitions. Values are not documented.`);
  sections.push("");
  const areas = envAreas(names);
  const counts = new Map<EnvArea, number>();
  for (const name of names) {
    const area = classifyEnvVar(name);
    counts.set(area, (counts.get(area) ?? 0) + 1);
  }
  const order: EnvArea[] = [
    "service URLs",
    "credentials",
    "ports",
    "timeouts",
    "audio/device",
    "watchdog/operations",
    "runtime",
  ];
  for (const area of order) {
    if (!areas.includes(area)) continue;
    sections.push(`- **${configAreaLabel(area)}:** ${counts.get(area) ?? 0}`);
  }
  sections.push("");
  sections.push(`Complete variable names: [\`configuration-inventory.md\`](${rel(config, "configurationInventory")}).`);
  sections.push("");
}

function pushCoverage(sections: string[], view: DocumentationViewModel): void {
  if (view.coverage.length === 0) return;
  sections.push("## Documentation Coverage");
  sections.push("");
  sections.push("Status is scanner coverage, not documentation completeness.");
  sections.push("");
  sections.push("| Area | Status | Notes |");
  sections.push("|------|--------|-------|");
  for (const area of view.coverage) {
    sections.push(`| ${area.area} | ${area.status} | ${area.notes} |`);
  }
  sections.push("");
}

function pushUnknowns(sections: string[], model: SystemModel): void {
  sections.push("## Known Technical Gaps / Unknowns");
  sections.push("");
  const unknowns = model.unknowns.filter((unk) => unk.area !== "Architecture Rationale");
  if (unknowns.length > 0) {
    for (const unk of unknowns) {
      sections.push(`- **${unk.area}:** ${unk.description}${unk.reason ? ` (${unk.reason})` : ""}`);
    }
  } else {
    sections.push("- No additional scanner unknowns were recorded beyond coverage limits.");
  }
  sections.push("");
  sections.push("Architecture selection rationale is not currently available as structured, validated repository evidence.");
  sections.push("");
}

function pushAppendices(sections: string[], config: DocforceConfig): void {
  sections.push("## Appendices / Supporting Artifacts");
  sections.push("");
  sections.push("Detailed inventories and diagrams (not duplicated here):");
  sections.push("");
  sections.push(`- [\`technology-inventory.md\`](${rel(config, "technologyInventory")})`);
  sections.push(`- [\`api-inventory.md\`](${rel(config, "apiInventory")})`);
  sections.push(`- [\`configuration-inventory.md\`](${rel(config, "configurationInventory")})`);
  sections.push(`- [\`dependency-graph.mmd\`](${rel(config, "dependencyGraph")})`);
  sections.push(`- [\`architecture-evidence.md\`](${rel(config, "architectureEvidence")})`);
  sections.push(`- [\`system-overview.mmd\`](${rel(config, "systemOverview")})`);
  sections.push(`- [\`software-architecture.mmd\`](${rel(config, "softwareArchitecture")})`);
  sections.push(`- [\`data-architecture.mmd\`](${rel(config, "dataArchitecture")})`);
  sections.push(`- [\`deployment-architecture.mmd\`](${rel(config, "deploymentArchitecture")})`);
  sections.push(`- [\`device-architecture.mmd\`](${rel(config, "deviceArchitecture")})`);
  sections.push(`- [\`technical-overview.md\`](${rel(config, "technicalOverview")})`);
  sections.push("");
}

function embedDiagram(sections: string[], diagram: string): void {
  if (diagram.includes("View unavailable:")) return;
  sections.push("```mermaid");
  sections.push(diagram.trim());
  sections.push("```");
  sections.push("");
}

function rel(config: DocforceConfig, key: Parameters<typeof resolveDocsOutputPath>[1]): string {
  const path = resolveDocsOutputPath(config.output.docs, key);
  return path.split("/").pop() ?? path;
}

function firstSentence(text: string): string {
  const trimmed = text.replace(/\s+/g, " ").trim();
  if (!trimmed) return "";
  const match = trimmed.match(/^[^.]+(?:\.)?/);
  return match?.[0]?.trim() ?? trimmed;
}

function verb(type: string): string {
  switch (type) {
    case "reads-from": return "reads from";
    case "writes-to": return "writes to";
    case "persists-to": return "persists to";
    default: return type;
  }
}

function httpPath(rel: Relationship): string | undefined {
  const paths = rel.evidence
    .filter((item) => item.evidenceType === "http-request-path")
    .map((item) => item.detail?.match(/(\/[A-Za-z0-9._~/-]+)/)?.[1])
    .filter((path): path is string => Boolean(path));
  const unique = [...new Set(paths)];
  return unique.length > 0 ? unique.join(", ") : undefined;
}

function flagshipServiceDetail(detail?: string): string | undefined {
  if (!detail) return undefined;
  const kept = detail.split("; ").filter((part) => !/^env\s+/i.test(part.trim()));
  return kept.length > 0 ? kept.join("; ") : undefined;
}

function article(word: string): "a" | "an" {
  return /^[aeiou]/i.test(word.trim()) ? "an" : "a";
}

function mountTarget(rel: Relationship): string | undefined {
  const detail = rel.evidence[0]?.detail ?? rel.description ?? "";
  const match = detail.match(/ at (\S+)$/);
  return match?.[1];
}

function labelDevice(model: SystemModel, id: string): string {
  const device = (model.devices ?? []).find((item) => item.id === id);
  if (device) return device.name;
  const fleet = model.infrastructure.find((item) => item.type === "device-fleet" && (`infra:${item.name}` === id || item.name === id));
  return fleet?.name ?? id.replace(/^.*:/, "");
}

function configAreaLabel(area: EnvArea): string {
  switch (area) {
    case "service URLs": return "service endpoints";
    case "credentials": return "credentials/secrets references";
    case "ports": return "ports";
    case "timeouts": return "timeout/retry settings";
    case "audio/device": return "audio/device settings";
    case "watchdog/operations": return "watchdog/operations settings";
    case "runtime": return "runtime";
    default: {
      const _exhaustive: never = area;
      return _exhaustive;
    }
  }
}
