import type { SystemModel } from "../model/types.js";
import type { DocforceConfig } from "../config/types.js";
import { buildDocumentationViewModel, overviewCategoryLabel } from "../view/buildViewModel.js";
import { presentationConfig } from "../view/presentationConfig.js";
import type { DocumentationViewModel, OverviewNode } from "../view/types.js";
import { summarizeComposeDetail } from "../view/envSummary.js";
import { aggregateContainerImages } from "../view/infraPresentation.js";
import { integrationLabel } from "../view/integrationLabels.js";

export function generateTechnicalOverview(model: SystemModel, config?: DocforceConfig): string {
  const view = buildDocumentationViewModel(model, presentationConfig(config));
  const sections: string[] = [];

  sections.push(`# ${model.product.name} — Technical Overview`);
  sections.push("");
  sections.push(`> Generated by DocForce from the repository's validated technical model.`);
  sections.push("");

  pushProductSummary(sections, model);
  pushArchitectureOverview(sections, model, view);
  pushLanguages(sections, model);
  pushMajorComponents(sections, view);
  pushApiSurface(sections, view);
  pushData(sections, model);
  pushIntegrations(sections, model);
  pushDeployment(sections, model);
  pushDevices(sections, model);
  pushCoverage(sections, model, view);

  sections.push("---");
  sections.push("");
  sections.push(`*Generated by DocForce. Do not edit manually — regenerate with \`npm run docforce\`.*`);
  sections.push("");

  return sections.join("\n");
}

function pushProductSummary(sections: string[], model: SystemModel): void {
  sections.push("## Product Technical Summary");
  sections.push("");
  sections.push(`**Name:** ${model.product.name}`);
  sections.push(`**Type:** ${model.product.type}`);
  sections.push(`**Description:** ${model.product.description}`);
  sections.push("");
}

function pushArchitectureOverview(
  sections: string[],
  model: SystemModel,
  view: DocumentationViewModel,
): void {
  if (view.overviewNodes.length === 0 && model.components.length === 0) return;

  sections.push("## Architecture Overview");
  sections.push("");
  const byCategory = groupOverview(view.overviewNodes);
  if (byCategory.length > 0) {
    sections.push("Major system categories derived from entity types:");
    sections.push("");
    for (const [category, nodes] of byCategory) {
      const names = nodes.map((n) => n.label).join(", ");
      sections.push(`- **${overviewCategoryLabel(category)}:** ${names}`);
    }
    sections.push("");
  }

  sections.push("Specialized architecture views:");
  sections.push("");
  sections.push("- [`system-overview.mmd`](system-overview.mmd)");
  sections.push("- [`software-architecture.mmd`](software-architecture.mmd)");
  sections.push("- [`deployment-architecture.mmd`](deployment-architecture.mmd)");
  sections.push("- [`data-architecture.mmd`](data-architecture.mmd)");
  sections.push("- [`device-architecture.mmd`](device-architecture.mmd)");
  sections.push("");
  sections.push("Detailed engineering artifacts: [`dependency-graph.mmd`](dependency-graph.mmd), [`architecture-evidence.md`](architecture-evidence.md).");
  sections.push("`architecture.mmd` is the Consumer #1-compatible system overview.");
  sections.push("");
}

function pushLanguages(sections: string[], model: SystemModel): void {
  if (model.runtime.length === 0 && model.languages.length === 0) return;
  sections.push("## Languages & Runtime");
  sections.push("");
  if (model.runtime.length > 0) {
    for (const rt of model.runtime) {
      sections.push(`- **${rt.name}**${rt.version ? ` (${rt.version})` : ""}`);
    }
  }
  if (model.languages.length > 0) {
    for (const lang of model.languages) {
      sections.push(`- **${lang.name}**${lang.version ? ` (${lang.version})` : ""}`);
    }
  }
  sections.push("");
}

function pushMajorComponents(sections: string[], view: DocumentationViewModel): void {
  if (view.components.length === 0) return;
  const major = view.components.filter((c) => c.presentation !== "utility");
  const utility = view.components.filter((c) => c.presentation === "utility");

  sections.push("## Major Software Components");
  sections.push("");
  if (major.length > 0) {
    sections.push("| Component | Path | Presentation | Type | Summary |");
    sections.push("|-----------|------|--------------|------|---------|");
    for (const comp of major) {
      sections.push(
        `| ${comp.displayName} | \`${comp.path}\` | ${comp.presentation} | ${comp.type} | ${comp.summary ?? "—"} |`,
      );
    }
    sections.push("");
  }
  if (utility.length > 0) {
    sections.push(
      `${utility.length} utility component${utility.length === 1 ? " is" : "s are"} omitted from this overview and remain in the System Model.`,
    );
    sections.push("");
  }
}

function pushApiSurface(sections: string[], view: DocumentationViewModel): void {
  if (view.apiRouteCount === 0) return;
  sections.push("## Local API Surface");
  sections.push("");
  sections.push(
    `${view.apiRouteCount} local API route${view.apiRouteCount === 1 ? " was" : "s were"} detected across ${view.apiGroupCount} top-level route group${view.apiGroupCount === 1 ? "" : "s"}.`,
  );
  sections.push("");
  sections.push("| Group | Routes |");
  sections.push("|-------|--------|");
  for (const group of view.apiGroups) {
    sections.push(`| \`${group.group}\` | ${group.routes.length} |`);
  }
  sections.push("");
  sections.push("See [`api-inventory.md`](api-inventory.md) for route paths, HTTP methods, and source files.");
  sections.push("");
}

function pushData(sections: string[], model: SystemModel): void {
  if (model.datastores.length === 0) return;
  sections.push("## Data & Storage");
  sections.push("");
  for (const ds of model.datastores) {
    const location = ds.location ? ` (${ds.location})` : "";
    sections.push(`- **${ds.name}** — ${ds.type}${location}`);
  }
  sections.push("");
}

function pushIntegrations(sections: string[], model: SystemModel): void {
  const integrations = model.integrations.filter((i) => i.type !== "system");
  if (integrations.length === 0) return;
  sections.push("## External Integrations");
  sections.push("");
  sections.push("| Integration | Type | Direction | Protocol |");
  sections.push("|-------------|------|-----------|----------|");
  for (const integ of integrations) {
    sections.push(
      `| ${integrationLabel(integ.name)} | ${integ.type} | ${integ.direction} | ${integ.protocol ?? "—"} |`,
    );
  }
  sections.push("");
}

function pushDeployment(sections: string[], model: SystemModel): void {
  if (model.infrastructure.length === 0) return;
  sections.push("## Deployment & Infrastructure");
  sections.push("");
  const byType = groupBy(model.infrastructure, (i) => i.type);
  const order = [
    "docker-service",
    "systemd-service",
    "docker-volume",
    "docker-network",
    "device-fleet",
    "container-image",
    "exposed-port",
    "systemd-dependency",
  ];
  const keys = [
    ...order.filter((type) => byType[type]),
    ...Object.keys(byType).filter((type) => !order.includes(type)),
  ];
  for (const type of keys) {
    const items = byType[type]!;
    sections.push(`### ${formatInfraType(type)}`);
    sections.push("");
    if (type === "container-image") {
      const aggregated = aggregateContainerImages(items);
      for (const image of aggregated) {
        const files = image.files.length > 0 ? ` (\`${image.files.join("`, `")}\`)` : "";
        sections.push(`- **${image.name}** — ${image.detail}${files}`);
      }
      sections.push("");
      continue;
    }
    if (type === "docker-service") {
      for (const item of items) {
        const detail = summarizeComposeDetail(item.detail);
        sections.push(`- **${item.name}**${detail ? ` — ${detail}` : ""}`);
      }
      sections.push("");
      const envMention = items.some((item) => /environment variable/.test(summarizeComposeDetail(item.detail)));
      if (envMention) {
        sections.push("Complete environment-variable names are listed in [`configuration-inventory.md`](configuration-inventory.md). Secret values are not documented.");
        sections.push("");
      }
      continue;
    }
    for (const item of items) {
      sections.push(`- **${item.name}**${item.detail ? ` — ${item.detail}` : ""}`);
    }
    sections.push("");
  }
  if (model.workflows.length > 0) {
    sections.push("### CI/CD workflows");
    sections.push("");
    for (const wf of model.workflows) {
      sections.push(`- **${wf.name}**${wf.trigger ? ` — ${wf.trigger}` : ""}`);
    }
    sections.push("");
  }
}

function pushDevices(sections: string[], model: SystemModel): void {
  const composeNames = new Set(
    model.infrastructure.filter((item) => item.type === "docker-service").map((item) => item.name),
  );
  const devices = (model.devices ?? []).filter(
    (device) => !(device.kind === "device-service" && composeNames.has(device.name)),
  );
  if (devices.length === 0) return;
  sections.push("## Device / Peripheral Interfaces");
  sections.push("");
  sections.push("| Name | Kind | Detail |");
  sections.push("|------|------|--------|");
  for (const device of devices) {
    sections.push(`| ${device.name} | ${device.kind} | ${device.detail ?? "—"} |`);
  }
  sections.push("");
}

function pushCoverage(
  sections: string[],
  model: SystemModel,
  view: DocumentationViewModel,
): void {
  sections.push("## Documentation Coverage & Unknowns");
  sections.push("");
  sections.push("Status is based on scanner coverage and unknowns, not percentages.");
  sections.push("");
  sections.push("| Area | Status | Notes |");
  sections.push("|------|--------|-------|");
  for (const area of view.coverage) {
    sections.push(`| ${area.area} | ${area.status} | ${area.notes} |`);
  }
  sections.push("");

  const unknowns = model.unknowns.filter((unk) => unk.area !== "Architecture Rationale");
  if (unknowns.length > 0) {
    sections.push("Repository unknowns (excluding architecture rationale, which is out of scope):");
    sections.push("");
    for (const unk of unknowns) {
      sections.push(`- **${unk.area}:** ${unk.description} (${unk.reason})`);
    }
    sections.push("");
  }
}

function groupOverview(nodes: readonly OverviewNode[]): [OverviewNode["category"], OverviewNode[]][] {
  const map = new Map<OverviewNode["category"], OverviewNode[]>();
  for (const node of nodes) {
    const list = map.get(node.category) ?? [];
    list.push(node);
    map.set(node.category, list);
  }
  return [...map.entries()];
}

function formatInfraType(type: string): string {
  const map: Record<string, string> = {
    "systemd-service": "Systemd Services",
    "systemd-dependency": "Service Dependencies",
    "container-image": "Container Images",
    "docker-service": "Docker Compose Services",
    "docker-volume": "Docker Compose Volumes",
    "docker-network": "Docker Compose Networks",
    "device-fleet": "Device Fleet",
    "exposed-port": "Exposed Ports",
  };
  return map[type] ?? capitalize(type);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/-/g, " ");
}

function groupBy<T>(items: readonly T[], keyFn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of items) {
    const key = keyFn(item);
    if (!result[key]) result[key] = [];
    result[key]!.push(item);
  }
  return result;
}
